{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "62de0405-548a-42ab-a35f-5860503aff95",
   "metadata": {},
   "outputs": [],
   "source": [
    "import mysql.connector as connector"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "52c5cc67-206a-4e31-b43c-4a9346a0e576",
   "metadata": {},
   "outputs": [],
   "source": [
    "connection = connector.connect(\n",
    "    user=\"dbcourse\",\n",
    "    password=\"DBc0urse123!!!\",\n",
    "    host=\"localhost\",\n",
    "    database=\"LittleLemonDM\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9824d237-91f3-4ba6-8e9a-b9bf4acedcb6",
   "metadata": {},
   "outputs": [],
   "source": [
    "cursor = connection.cursor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0ed4e342-7c3b-42b5-9183-05cc4b92693c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Bookings',)\n",
      "('CustomerDetails',)\n",
      "('MenuItems',)\n",
      "('OrderDeliveryStatus',)\n",
      "('OrderMenuItems',)\n",
      "('Orders',)\n",
      "('ordersview',)\n",
      "('StaffInfo',)\n"
     ]
    }
   ],
   "source": [
    "cursor.execute(\"SHOW TABLES;\")\n",
    "results = cursor.fetchall()\n",
    "\n",
    "for table in results:\n",
    "    print(table)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "82f52dbf-70a9-48da-bd2c-b6e21800d211",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Pansie Alldis', Decimal('465.00'))\n",
      "('Xymenes Hands', Decimal('104.07'))\n",
      "('Lulu Hastin', Decimal('125.99'))\n",
      "('Salvidor Francesch', Decimal('337.50'))\n",
      "('Noni Quickenden', Decimal('465.00'))\n",
      "('Jilleen Foux', Decimal('125.99'))\n",
      "('Grenville Hyne', Decimal('285.00'))\n",
      "('Ram Sinclaire', Decimal('152.40'))\n",
      "('Jilly Bursnoll', Decimal('199.76'))\n",
      "('Gabe Boyan', Decimal('252.41'))\n",
      "('Anna-maria Neilan', Decimal('66.86'))\n",
      "('Gage Tocknell', Decimal('112.50'))\n",
      "('Dennie Lilloe', Decimal('137.76'))\n",
      "('Harriott Manby', Decimal('125.99'))\n",
      "('Cyril Copelli', Decimal('285.00'))\n",
      "('Fidelity Banham', Decimal('480.00'))\n",
      "('Anna-diane Kopps', Decimal('78.12'))\n",
      "('Raquel Borham', Decimal('352.50'))\n",
      "('Alan Paskell', Decimal('337.50'))\n",
      "('Pierson Baal', Decimal('112.50'))\n",
      "('Darla Kubacek', Decimal('78.12'))\n",
      "('Eva Dulake', Decimal('187.50'))\n",
      "('Christabella Coathup', Decimal('186.93'))\n",
      "('Karlene Whetson', Decimal('352.50'))\n",
      "('Everard Trasler', Decimal('465.00'))\n",
      "('Paloma Spellar', Decimal('285.00'))\n",
      "('Maryjo Strangwood', Decimal('216.14'))\n",
      "('Deane Benbough', Decimal('337.50'))\n",
      "('Pablo Dracksford', Decimal('465.00'))\n",
      "('Durand Kitt', Decimal('137.76'))\n",
      "('Jessey Doddrell', Decimal('330.00'))\n",
      "('Jacky Shapero', Decimal('285.00'))\n",
      "('Laurianne Diehn', Decimal('330.00'))\n",
      "('Gauthier Sapshed', Decimal('112.50'))\n",
      "('Westbrooke Blindt', Decimal('187.50'))\n",
      "('Sherilyn Ilewicz', Decimal('78.12'))\n",
      "('Annaliese Brunsden', Decimal('330.00'))\n",
      "('Fawnia Bartosch', Decimal('66.86'))\n",
      "('Damiano Yurasov', Decimal('465.00'))\n",
      "('Megan Beddows', Decimal('352.50'))\n",
      "('Jerome Ovitts', Decimal('139.70'))\n",
      "('Freida Nannizzi', Decimal('179.70'))\n",
      "('Obidiah Zanicchi', Decimal('112.50'))\n",
      "('Aime Ferry', Decimal('137.76'))\n",
      "('Dareen Soutar', Decimal('216.14'))\n",
      "('Stan Clethro', Decimal('252.41'))\n",
      "('Sol Hynam', Decimal('337.50'))\n",
      "('Maribelle Allcroft', Decimal('352.50'))\n",
      "('Nerty Green', Decimal('465.00'))\n",
      "('Roddie Winterbotham', Decimal('199.76'))\n",
      "('Egon Lawrance', Decimal('125.99'))\n",
      "('Mirna Rosita', Decimal('330.00'))\n",
      "('Nelli Myrie', Decimal('480.00'))\n",
      "('Constantina Mottley', Decimal('78.12'))\n",
      "('Althea Jaggli', Decimal('315.00'))\n",
      "('Ginevra Pally', Decimal('252.41'))\n",
      "('Hedi Pellington', Decimal('152.40'))\n",
      "('Rubin Ind', Decimal('137.76'))\n",
      "('Petronille Southwood', Decimal('125.99'))\n",
      "('Merwin Pikhno', Decimal('187.50'))\n",
      "('Desdemona Dobbinson', Decimal('216.14'))\n",
      "('Lucilia Sandeman', Decimal('352.50'))\n",
      "('Ingamar Forker', Decimal('104.07'))\n",
      "('Hermine Dorton', Decimal('78.12'))\n",
      "('Valma Brideau', Decimal('78.12'))\n",
      "('Marcile Meffen', Decimal('315.00'))\n",
      "('Katy Pine', Decimal('465.00'))\n",
      "('Jordan Donner', Decimal('337.50'))\n",
      "('Forester Buxcey', Decimal('465.00'))\n",
      "('Ethelind Schnieder', Decimal('199.76'))\n",
      "('Elsworth Stannas', Decimal('139.70'))\n",
      "('Tiffani Halstead', Decimal('137.76'))\n",
      "('Aluin McUre', Decimal('315.00'))\n",
      "('Paulie Lemerle', Decimal('104.07'))\n",
      "('Lew Allot', Decimal('152.40'))\n",
      "('Berne Banbury', Decimal('187.50'))\n",
      "('Chrotoem Estevez', Decimal('315.00'))\n",
      "('Lottie Schultheiss', Decimal('147.00'))\n",
      "('Othella Flood', Decimal('480.00'))\n",
      "('Giusto Sheavills', Decimal('352.50'))\n",
      "('Kelwin Ryle', Decimal('186.93'))\n",
      "('Jobie Coaten', Decimal('199.76'))\n",
      "('Gianni Aistrop', Decimal('315.00'))\n",
      "('Virginie McGrey', Decimal('216.14'))\n",
      "('Bertrand Bilton', Decimal('465.00'))\n",
      "('Natasha Cool', Decimal('337.50'))\n",
      "('Aurie Unthank', Decimal('187.50'))\n",
      "('Robbin Shottin', Decimal('199.76'))\n",
      "('Ally McBrearty', Decimal('216.14'))\n",
      "('Boot Burree', Decimal('187.50'))\n",
      "('Mignonne Shepland', Decimal('337.50'))\n",
      "('Nelie Cleare', Decimal('152.40'))\n",
      "('Serene Steadman', Decimal('330.00'))\n",
      "(\"Susette O'Neil\", Decimal('480.00'))\n",
      "('Cathleen Gooday', Decimal('480.00'))\n",
      "('Essie Hagland', Decimal('187.50'))\n",
      "('Annice Maxworthy', Decimal('186.93'))\n",
      "('Walther Rablin', Decimal('337.50'))\n",
      "('Alyse Pimlett', Decimal('216.14'))\n",
      "('Dill Beardshall', Decimal('465.00'))\n",
      "('Hermione Tire', Decimal('66.86'))\n",
      "(\"Web O'Howbane\", Decimal('465.00'))\n",
      "('Kimble Wayvill', Decimal('199.76'))\n",
      "('Steffane Karpol', Decimal('66.86'))\n",
      "('Dominick Crafts', Decimal('330.00'))\n",
      "('Odilia Bockett', Decimal('104.07'))\n",
      "('Ariadne McCrie', Decimal('187.50'))\n",
      "('Theadora Huetson', Decimal('78.12'))\n",
      "('Herve Tunmore', Decimal('186.93'))\n",
      "('Marena Jacox', Decimal('216.14'))\n",
      "('Ali Einchcombe', Decimal('315.00'))\n",
      "('Ezequiel Benion', Decimal('187.50'))\n",
      "('Silas Asson', Decimal('352.50'))\n",
      "('Jesse Martelet', Decimal('186.93'))\n",
      "('Lexie Spinetti', Decimal('152.40'))\n",
      "('Nev Bompas', Decimal('199.76'))\n",
      "('Weston Dearden', Decimal('137.76'))\n",
      "('Natty Murt', Decimal('285.00'))\n",
      "('Kiley Nare', Decimal('186.93'))\n",
      "('Ondrea Keyser', Decimal('104.07'))\n",
      "('Tabbie Conboy', Decimal('137.76'))\n",
      "('Schuyler Walewski', Decimal('179.70'))\n",
      "('Worth Laweles', Decimal('465.00'))\n",
      "('Maible Dalgarno', Decimal('147.00'))\n",
      "('Camille Symmons', Decimal('112.50'))\n",
      "('Ermina Kitter', Decimal('147.00'))\n",
      "('Ryley McKillop', Decimal('252.41'))\n",
      "('Jackelyn Jacox', Decimal('187.50'))\n",
      "('Dietrich Feetham', Decimal('216.14'))\n",
      "('Stewart Keppe', Decimal('330.00'))\n",
      "('Celinda Mamwell', Decimal('216.14'))\n",
      "('Philomena Petracchi', Decimal('112.50'))\n",
      "('Rosanne Zorzutti', Decimal('152.40'))\n",
      "('Melisent Claessens', Decimal('285.00'))\n",
      "('Stirling Santry', Decimal('179.70'))\n",
      "('Orel Gawthrope', Decimal('139.70'))\n",
      "('Jazmin Torald', Decimal('152.40'))\n",
      "('Marillin Tieman', Decimal('252.41'))\n",
      "('Jenda Castellino', Decimal('179.70'))\n",
      "('Itch Merle', Decimal('137.76'))\n",
      "(\"Goldie O'Sherrin\", Decimal('315.00'))\n",
      "('Julius Scutchin', Decimal('199.76'))\n",
      "('Dalila Baldree', Decimal('137.76'))\n",
      "('Steward Pettinger', Decimal('480.00'))\n",
      "('Morgan Gouldeby', Decimal('285.00'))\n",
      "('Melloney Schimke', Decimal('179.70'))\n",
      "('Magdalen Lacheze', Decimal('147.00'))\n",
      "('Blancha Trippack', Decimal('216.14'))\n",
      "('Boot Terbeck', Decimal('337.50'))\n",
      "('Tyson Gahagan', Decimal('179.70'))\n",
      "('Giffy Wreath', Decimal('78.12'))\n",
      "('Dulcie Lax', Decimal('330.00'))\n",
      "('Fielding Struys', Decimal('252.41'))\n",
      "('Wanda Ramas', Decimal('216.14'))\n",
      "('Gigi Trunchion', Decimal('216.14'))\n",
      "('Waylan Grieve', Decimal('285.00'))\n",
      "('Almeta Laird-Craig', Decimal('337.50'))\n",
      "('Ezri Gouck', Decimal('137.76'))\n",
      "('Karia Sonier', Decimal('66.86'))\n",
      "('Linc Martynov', Decimal('104.07'))\n",
      "('Evelyn Serrier', Decimal('186.93'))\n",
      "('Callie Dunning', Decimal('104.07'))\n",
      "('Rowena Santori', Decimal('179.70'))\n",
      "('Charlot Warkup', Decimal('152.40'))\n",
      "('Sherm Probat', Decimal('139.70'))\n",
      "('Maddie Raw', Decimal('480.00'))\n",
      "('Cynthy Stovold', Decimal('66.86'))\n",
      "('Ives Darmody', Decimal('66.86'))\n",
      "('Natala Stobbe', Decimal('315.00'))\n",
      "('Beret Behneke', Decimal('216.14'))\n",
      "('Kiersten Dalliwater', Decimal('330.00'))\n",
      "('Charin Pinckard', Decimal('216.14'))\n",
      "(\"Melinda O'Brogan\", Decimal('78.12'))\n",
      "('Clevey Garfit', Decimal('179.70'))\n",
      "('Renata Vlach', Decimal('337.50'))\n",
      "('Chaddy Mangeney', Decimal('330.00'))\n",
      "('Devy Hookes', Decimal('139.70'))\n",
      "('Dniren Copperwaite', Decimal('139.70'))\n",
      "('Niles MacMenamy', Decimal('78.12'))\n",
      "('Jackie Kment', Decimal('179.70'))\n",
      "('Kariotta Core', Decimal('152.40'))\n",
      "('Waldo Tomkiss', Decimal('199.76'))\n",
      "('Terencio Loche', Decimal('112.50'))\n",
      "('Sue Fargie', Decimal('216.14'))\n",
      "('Tiertza Barford', Decimal('480.00'))\n",
      "('Taffy Shipcott', Decimal('480.00'))\n",
      "('Sibyl Cuphus', Decimal('152.40'))\n",
      "('Bobby Blazewski', Decimal('187.50'))\n",
      "('Florinda Cellier', Decimal('252.41'))\n",
      "('Reggie Hallaways', Decimal('66.86'))\n",
      "('Hallie Roddam', Decimal('352.50'))\n",
      "('Junie Older', Decimal('465.00'))\n",
      "('Raymond Cranage', Decimal('252.41'))\n",
      "('Georgeanna Boulton', Decimal('139.70'))\n",
      "('Porty Auston', Decimal('66.86'))\n",
      "('Steffie Slemmonds', Decimal('112.50'))\n",
      "('Ynez Hows', Decimal('352.50'))\n",
      "('Julina Di Franceschi', Decimal('337.50'))\n",
      "('Hakeem Leadston', Decimal('187.50'))\n",
      "('Enrika Marty', Decimal('152.40'))\n",
      "('Forest Cole', Decimal('315.00'))\n",
      "('Gavra Breslin', Decimal('147.00'))\n",
      "('Karee Colchett', Decimal('216.14'))\n",
      "('Thorin Jolliman', Decimal('137.76'))\n",
      "('Gizela Northover', Decimal('330.00'))\n",
      "('Margarita Mancktelow', Decimal('252.41'))\n",
      "('Myra Zaczek', Decimal('330.00'))\n",
      "('Averell Joint', Decimal('465.00'))\n",
      "('Jonell Aiton', Decimal('186.93'))\n",
      "('Allyce Berthon', Decimal('112.50'))\n",
      "('Theda Jagoe', Decimal('152.40'))\n",
      "('Far Emmanuele', Decimal('137.76'))\n",
      "('Guthry Galpin', Decimal('285.00'))\n",
      "('Cordelia Whicher', Decimal('337.50'))\n",
      "('Mickie Alred', Decimal('112.50'))\n",
      "('Cahra Delacoste', Decimal('66.86'))\n",
      "('Bennett Pendered', Decimal('78.12'))\n",
      "('Pietra Paute', Decimal('152.40'))\n",
      "('Heida Bohden', Decimal('125.99'))\n",
      "('Anatole Desforges', Decimal('66.86'))\n",
      "('Kaylyn Colebourne', Decimal('315.00'))\n",
      "('Yvon Chasmor', Decimal('330.00'))\n",
      "('Yorgos Staite', Decimal('112.50'))\n",
      "('Kally Biers', Decimal('125.99'))\n",
      "('Alena Geratasch', Decimal('315.00'))\n",
      "('Agretha Dutteridge', Decimal('285.00'))\n",
      "('Maison Shoreson', Decimal('112.50'))\n",
      "('Barnabas Casson', Decimal('465.00'))\n",
      "('Araldo Bramhall', Decimal('137.76'))\n",
      "('Noby Torvey', Decimal('337.50'))\n",
      "('Cornelius Harkess', Decimal('285.00'))\n",
      "('Calla Lambal', Decimal('315.00'))\n",
      "('Peggie Biddles', Decimal('252.41'))\n",
      "('Cristabel Nutty', Decimal('216.14'))\n",
      "('Paco Towersey', Decimal('78.12'))\n",
      "('Koral Stampfer', Decimal('179.70'))\n",
      "('Nickolai Balmer', Decimal('285.00'))\n",
      "('Cal Rorke', Decimal('139.70'))\n",
      "('Arnie Jay', Decimal('315.00'))\n",
      "('Annamarie Taylot', Decimal('112.50'))\n",
      "('Roosevelt Grigg', Decimal('112.50'))\n",
      "('Aube Francescuzzi', Decimal('125.99'))\n",
      "('Dorie Cammell', Decimal('104.07'))\n",
      "('Zora Hanalan', Decimal('252.41'))\n",
      "('Alfreda Chasmer', Decimal('199.76'))\n",
      "('Norby Foord', Decimal('152.40'))\n",
      "('Miquela Dutnell', Decimal('337.50'))\n",
      "('Ulberto Alyutin', Decimal('216.14'))\n",
      "('Teriann Olivari', Decimal('66.86'))\n",
      "('Tersina Wolfer', Decimal('330.00'))\n",
      "('Mathew Groucutt', Decimal('139.70'))\n",
      "('Zorana Diggin', Decimal('315.00'))\n",
      "('Graham Rumford', Decimal('152.40'))\n",
      "('Uriel Grooby', Decimal('187.50'))\n",
      "('Heinrick Setchfield', Decimal('315.00'))\n",
      "('Ezequiel Cunniff', Decimal('125.99'))\n",
      "('Carena Nucator', Decimal('139.70'))\n",
      "('Andonis Rawling', Decimal('480.00'))\n",
      "('Kellina Oates', Decimal('186.93'))\n",
      "('Sue Voyce', Decimal('139.70'))\n",
      "('Hulda Nayshe', Decimal('66.86'))\n",
      "('Deloria Hannen', Decimal('186.93'))\n",
      "('Yankee Penright', Decimal('147.00'))\n",
      "('Ansell Lethlay', Decimal('179.70'))\n",
      "('Riordan Wormald', Decimal('330.00'))\n",
      "('Korney Buffery', Decimal('352.50'))\n",
      "('Elora Eliesco', Decimal('152.40'))\n",
      "('Lenci McFadzean', Decimal('179.70'))\n",
      "('Hamlen Mashro', Decimal('186.93'))\n",
      "('Sully Cunney', Decimal('104.07'))\n",
      "('Lind Haggath', Decimal('465.00'))\n",
      "('Braden Bartolacci', Decimal('187.50'))\n",
      "('Morganne Brecknell', Decimal('285.00'))\n",
      "('Guthrey Juara', Decimal('147.00'))\n",
      "('Dacey Witherden', Decimal('285.00'))\n",
      "('Gail Grigaut', Decimal('199.76'))\n",
      "('Bambie Frears', Decimal('66.86'))\n",
      "('Elke Dumingos', Decimal('187.50'))\n",
      "('Son Hurworth', Decimal('147.00'))\n",
      "('Horatio Codi', Decimal('139.70'))\n",
      "('Ignace Cooney', Decimal('315.00'))\n",
      "('Carleen Gyver', Decimal('199.76'))\n",
      "('Rhetta Nevill', Decimal('330.00'))\n",
      "('Lethia Bodechon', Decimal('78.12'))\n",
      "('Hastie Charopen', Decimal('315.00'))\n",
      "('Araldo Gutman', Decimal('112.50'))\n",
      "('Derry Davis', Decimal('104.07'))\n",
      "('Fayre Crocket', Decimal('252.41'))\n",
      "('Nathanil Eykel', Decimal('78.12'))\n",
      "('Ely Doodson', Decimal('78.12'))\n",
      "('Alvan Winspare', Decimal('199.76'))\n",
      "('Forster Pervew', Decimal('315.00'))\n",
      "('Mureil Codman', Decimal('330.00'))\n",
      "('Grenville Bottomore', Decimal('465.00'))\n",
      "('Selena Relton', Decimal('179.70'))\n",
      "('Adaline Reichartz', Decimal('186.93'))\n",
      "('Den Coppock.', Decimal('330.00'))\n",
      "('Olly Dobbinson', Decimal('337.50'))\n",
      "('Gusella Wadeling', Decimal('285.00'))\n",
      "('Kalindi Ryman', Decimal('137.76'))\n",
      "('Nadean Elves', Decimal('66.86'))\n",
      "('Ham Penhall', Decimal('186.93'))\n",
      "('Wakefield Strotton', Decimal('78.12'))\n",
      "('Dominga Mc Kellen', Decimal('66.86'))\n",
      "('Dennison Qusklay', Decimal('152.40'))\n",
      "('Erinn Vannar', Decimal('337.50'))\n",
      "('Michaela Babcock', Decimal('179.70'))\n",
      "('Rene Clements', Decimal('187.50'))\n",
      "('Evvie Crossby', Decimal('139.70'))\n",
      "('Hedi Chadwin', Decimal('352.50'))\n",
      "('Zorine Delacourt', Decimal('315.00'))\n",
      "(\"Gradey O'Gready\", Decimal('147.00'))\n",
      "('Joycelin Loghan', Decimal('66.86'))\n",
      "('Paton Fritzer', Decimal('147.00'))\n",
      "('Jenilee Ricardou', Decimal('112.50'))\n",
      "('Katie Betancourt', Decimal('152.40'))\n",
      "('Tildy Shanks', Decimal('112.50'))\n",
      "('Kellyann Sambells', Decimal('330.00'))\n",
      "('Godfrey Jellicorse', Decimal('139.70'))\n",
      "('Rudolph Brozek', Decimal('147.00'))\n",
      "('Adrianne Freeland', Decimal('186.93'))\n",
      "('Melesa Halahan', Decimal('152.40'))\n",
      "('Ardene Davydenko', Decimal('199.76'))\n",
      "('Elvina McGlynn', Decimal('112.50'))\n",
      "('Haily Izakoff', Decimal('315.00'))\n",
      "('Currie Fidell', Decimal('337.50'))\n",
      "('Jillayne Gaiford', Decimal('352.50'))\n",
      "('Hinda Giacopetti', Decimal('104.07'))\n",
      "('Delly Ventum', Decimal('252.41'))\n",
      "('Reginauld Kelemen', Decimal('104.07'))\n",
      "('Barnabas Gerrell', Decimal('125.99'))\n",
      "('Susie Torrisi', Decimal('152.40'))\n",
      "('Curry Able', Decimal('315.00'))\n",
      "('Charil Fanton', Decimal('66.86'))\n",
      "('Colver McChesney', Decimal('112.50'))\n",
      "('Tedda Plumridge', Decimal('216.14'))\n",
      "('Sandor Barradell', Decimal('104.07'))\n",
      "('Devland Pagett', Decimal('112.50'))\n",
      "('Lyndel Rodwell', Decimal('187.50'))\n",
      "('Coralie Keenlayside', Decimal('252.41'))\n",
      "('Kameko Cockton', Decimal('252.41'))\n",
      "('Cecilia Swinbourne', Decimal('104.07'))\n",
      "('Dodi Lenglet', Decimal('480.00'))\n",
      "('Eyde Ellerton', Decimal('139.70'))\n",
      "('Locke Janaway', Decimal('480.00'))\n",
      "('Jozef Godson', Decimal('66.86'))\n",
      "('George Woodeson', Decimal('66.86'))\n",
      "('Tricia Bellsham', Decimal('330.00'))\n",
      "('Vaughan Gorch', Decimal('352.50'))\n",
      "('Maybelle Bellows', Decimal('187.50'))\n",
      "('Karel Welband', Decimal('125.99'))\n",
      "('Livvyy Grombridge', Decimal('112.50'))\n",
      "('Alison Jamieson', Decimal('137.76'))\n",
      "('Dodi Basindale', Decimal('139.70'))\n",
      "('Raye Fyldes', Decimal('480.00'))\n",
      "('Chris Gummer', Decimal('78.12'))\n",
      "('Stephi Broose', Decimal('137.76'))\n",
      "('Christen Jedrachowicz', Decimal('465.00'))\n",
      "('Sindee Drynan', Decimal('480.00'))\n",
      "('Mill Lambell', Decimal('465.00'))\n",
      "('Sayer Goudman', Decimal('352.50'))\n",
      "('Amaleta Brattan', Decimal('152.40'))\n",
      "('Merrill Baudon', Decimal('330.00'))\n",
      "('Saw Aspenlon', Decimal('104.07'))\n",
      "('Kym Lepard', Decimal('480.00'))\n",
      "('Tammara Burgyn', Decimal('187.50'))\n",
      "('Lorna Bogart', Decimal('152.40'))\n",
      "('Virginie Lammas', Decimal('480.00'))\n",
      "(\"Lawrence O'Cahey\", Decimal('480.00'))\n",
      "('Galina Whaites', Decimal('216.14'))\n",
      "('Sorcha Beesley', Decimal('66.86'))\n",
      "('Borden Hacking', Decimal('78.12'))\n",
      "('Allie Turbard', Decimal('179.70'))\n",
      "('Skippy McIlwain', Decimal('125.99'))\n",
      "('Roth Cousans', Decimal('199.76'))\n",
      "(\"Mikael O'Keevan\", Decimal('179.70'))\n",
      "('Haslett Jenkyn', Decimal('112.50'))\n",
      "('Adham Heyns', Decimal('112.50'))\n",
      "('Granger Aiers', Decimal('104.07'))\n",
      "('Antonella Ochterlony', Decimal('186.93'))\n",
      "('Liam Downing', Decimal('179.70'))\n",
      "('Dal Raper', Decimal('352.50'))\n",
      "('Salem Morgen', Decimal('147.00'))\n",
      "('Henryetta Kempster', Decimal('285.00'))\n",
      "('Emmerich Ochterlony', Decimal('252.41'))\n",
      "('Jakie Bullan', Decimal('252.41'))\n",
      "('Reta Leipoldt', Decimal('330.00'))\n",
      "('Cele Dunster', Decimal('125.99'))\n",
      "('Calvin Aucock', Decimal('137.76'))\n",
      "('Pietra Dibdall', Decimal('216.14'))\n",
      "('Steward Lavies', Decimal('104.07'))\n",
      "('Ludwig Fuxman', Decimal('104.07'))\n",
      "('Konrad Standering', Decimal('104.07'))\n",
      "('Hana Livesay', Decimal('186.93'))\n",
      "('Shelbi Grishakov', Decimal('252.41'))\n",
      "('Jarib Cranke', Decimal('465.00'))\n",
      "('Trixy Southwick', Decimal('125.99'))\n",
      "('Barb Murfett', Decimal('137.76'))\n",
      "('Roch Panchen', Decimal('147.00'))\n",
      "('Doug Logg', Decimal('465.00'))\n",
      "('Willi Voce', Decimal('337.50'))\n",
      "(\"Cynthea O'Hickee\", Decimal('465.00'))\n",
      "('Germaine Vallack', Decimal('480.00'))\n",
      "('Henrie Ledward', Decimal('199.76'))\n",
      "('Brook Begent', Decimal('125.99'))\n",
      "('Antonino McMains', Decimal('187.50'))\n",
      "('Bibbie Bover', Decimal('137.76'))\n",
      "('Boniface Giovannilli', Decimal('352.50'))\n",
      "(\"Halette O'Hanley\", Decimal('112.50'))\n",
      "('Nertie Igglesden', Decimal('315.00'))\n",
      "('Flem Haibel', Decimal('104.07'))\n",
      "('Florella Reape', Decimal('66.86'))\n",
      "('Carroll Tear', Decimal('252.41'))\n",
      "('Stephanie Uman', Decimal('104.07'))\n",
      "('Annmarie Bountiff', Decimal('337.50'))\n",
      "('Melodee Gartshore', Decimal('199.76'))\n",
      "('Clive Crammy', Decimal('337.50'))\n",
      "('Shandeigh Andreas', Decimal('330.00'))\n",
      "('Gwenora Beauchamp', Decimal('78.12'))\n",
      "('Granville Mallison', Decimal('480.00'))\n",
      "('Mart Malsher', Decimal('285.00'))\n",
      "('Maryellen Gligori', Decimal('216.14'))\n",
      "('Zolly Heinzel', Decimal('179.70'))\n",
      "('Gerta Hehir', Decimal('186.93'))\n",
      "('Herculie Eastment', Decimal('330.00'))\n",
      "('Reuben Iannello', Decimal('147.00'))\n",
      "('Debbie Noteyoung', Decimal('125.99'))\n",
      "('Wandie Yeeles', Decimal('252.41'))\n",
      "('Gualterio Paget', Decimal('352.50'))\n",
      "('Brandon Cocklie', Decimal('480.00'))\n",
      "('Jenn Josephoff', Decimal('104.07'))\n",
      "('Brynn Roset', Decimal('66.86'))\n",
      "('Ximenez Meredith', Decimal('152.40'))\n",
      "('Alberik Fancy', Decimal('78.12'))\n",
      "('Malchy Huddlestone', Decimal('179.70'))\n",
      "('Saul Parsonage', Decimal('187.50'))\n",
      "('Nicole Linnit', Decimal('104.07'))\n",
      "('Verena Garman', Decimal('112.50'))\n",
      "('Melita Drinkale', Decimal('139.70'))\n",
      "('Emilie Faircley', Decimal('179.70'))\n",
      "('Alida Dumphy', Decimal('199.76'))\n",
      "(\"Danna O'Nion\", Decimal('216.14'))\n",
      "(\"Korney O'Carney\", Decimal('137.76'))\n",
      "('Tanner Garner', Decimal('186.93'))\n",
      "('Cathee Briscam', Decimal('112.50'))\n",
      "('Hurlee Dhennin', Decimal('139.70'))\n",
      "('Gardy Neljes', Decimal('480.00'))\n",
      "('Gerta Sanday', Decimal('199.76'))\n",
      "('Vincent Boarer', Decimal('186.93'))\n",
      "('Gabey Macewan', Decimal('465.00'))\n",
      "('Pen Pruce', Decimal('179.70'))\n",
      "('Padraic Zanutti', Decimal('480.00'))\n",
      "('Joanie Swindley', Decimal('337.50'))\n",
      "('Leslie Noden', Decimal('187.50'))\n",
      "('Lilyan Schohier', Decimal('179.70'))\n",
      "('Gawain Willmont', Decimal('137.76'))\n",
      "('Leonora Tullett', Decimal('147.00'))\n",
      "('Ilario Michie', Decimal('330.00'))\n",
      "('Rosaleen Ionnisian', Decimal('199.76'))\n",
      "('Berkley Petrashov', Decimal('152.40'))\n",
      "('Alberik Rowcastle', Decimal('252.41'))\n",
      "('Kenna Lideard', Decimal('179.70'))\n",
      "('Veronique Caramuscia', Decimal('78.12'))\n",
      "('Brook Rainger', Decimal('465.00'))\n",
      "('Baxy Dunkerley', Decimal('216.14'))\n",
      "('Pauline Danihelka', Decimal('137.76'))\n",
      "('Ag Gasking', Decimal('147.00'))\n",
      "('Veradis Tiddy', Decimal('199.76'))\n",
      "('Tibold MacGorley', Decimal('330.00'))\n",
      "('Mary Jellett', Decimal('199.76'))\n",
      "('Charisse Risso', Decimal('199.76'))\n",
      "('Riccardo Jahner', Decimal('330.00'))\n",
      "('Terry Iannitti', Decimal('199.76'))\n",
      "('Horatio Lundy', Decimal('252.41'))\n",
      "('Tiertza Doogan', Decimal('112.50'))\n",
      "('Jerrome Drohan', Decimal('147.00'))\n",
      "('Maressa Fruish', Decimal('285.00'))\n",
      "('Cirilo Koschek', Decimal('125.99'))\n",
      "('Ario Meekin', Decimal('104.07'))\n",
      "('Caterina Rosenzwig', Decimal('147.00'))\n",
      "('Dicky Van der Son', Decimal('66.86'))\n",
      "('Meg Reburn', Decimal('480.00'))\n",
      "('Marielle Buffey', Decimal('137.76'))\n",
      "('Moishe Constant', Decimal('147.00'))\n",
      "('Krishnah Pearch', Decimal('66.86'))\n",
      "('Jory Glave', Decimal('186.93'))\n",
      "('Carlin Brabon', Decimal('465.00'))\n",
      "('Joline Cancelier', Decimal('480.00'))\n",
      "('Kellby Quarterman', Decimal('315.00'))\n",
      "('Dorise Reames', Decimal('152.40'))\n",
      "('Felice Fiddler', Decimal('187.50'))\n",
      "('Malina Pengelly', Decimal('152.40'))\n",
      "('Kathleen Mac Giolla Pheadair', Decimal('187.50'))\n",
      "('Esra Mc Meekan', Decimal('315.00'))\n",
      "('Carol-jean Croston', Decimal('186.93'))\n",
      "('Durante Bullers', Decimal('139.70'))\n",
      "('Koo Vinick', Decimal('216.14'))\n",
      "('Spenser Wandless', Decimal('137.76'))\n",
      "('Jard Adderson', Decimal('330.00'))\n",
      "('Jehu Dauney', Decimal('66.86'))\n",
      "('Kele Bracknell', Decimal('139.70'))\n",
      "('Orelle Beadel', Decimal('199.76'))\n",
      "('Jere Whitebrook', Decimal('147.00'))\n",
      "('Cornelia Rowth', Decimal('152.40'))\n",
      "('Ogdon Petr', Decimal('104.07'))\n",
      "('Keane Wait', Decimal('147.00'))\n",
      "('Harry Beak', Decimal('66.86'))\n",
      "('Enriqueta Kirwin', Decimal('352.50'))\n",
      "('Evan Goldsbury', Decimal('125.99'))\n",
      "('Hymie Meadowcroft', Decimal('352.50'))\n",
      "('Ives Armstead', Decimal('480.00'))\n",
      "('Chauncey Barrott', Decimal('187.50'))\n",
      "('Noel Ladley', Decimal('137.76'))\n",
      "('Roanna Safont', Decimal('315.00'))\n",
      "('Gregg Yellowlea', Decimal('78.12'))\n",
      "('Elisabetta Jacke', Decimal('352.50'))\n",
      "('Thorny Westrip', Decimal('352.50'))\n",
      "('Janeva Silman', Decimal('315.00'))\n",
      "('Karissa Sancraft', Decimal('139.70'))\n",
      "('Kore Smurfit', Decimal('186.93'))\n",
      "('Devonne Yanuk', Decimal('187.50'))\n",
      "('Lorette Golsthorp', Decimal('66.86'))\n",
      "('Amye Limbert', Decimal('480.00'))\n",
      "(\"Tatiania O'Crigane\", Decimal('104.07'))\n",
      "('Mateo Wightman', Decimal('179.70'))\n",
      "('Filmer Floyd', Decimal('252.41'))\n",
      "('Sheela Stein', Decimal('187.50'))\n",
      "('Wyn Attwoull', Decimal('186.93'))\n",
      "('Elvira Beverstock', Decimal('179.70'))\n",
      "('Law Leinweber', Decimal('216.14'))\n",
      "('Gallagher Benyon', Decimal('337.50'))\n",
      "('Stormi Duddin', Decimal('147.00'))\n",
      "('Sharon Lazare', Decimal('352.50'))\n",
      "('Giustina Thorne', Decimal('465.00'))\n",
      "('Faith Grushin', Decimal('78.12'))\n",
      "('Isador Saffen', Decimal('179.70'))\n",
      "('Biddy Spadoni', Decimal('139.70'))\n",
      "('Laney Fadden', Decimal('187.50'))\n",
      "('Gloriane Allsepp', Decimal('179.70'))\n",
      "('Florella McMullen', Decimal('125.99'))\n",
      "('Marys Offen', Decimal('337.50'))\n",
      "('Desiri Issac', Decimal('112.50'))\n",
      "('Cleon Moreton', Decimal('352.50'))\n",
      "('Judy Swainson', Decimal('112.50'))\n",
      "('Mable Browncey', Decimal('179.70'))\n",
      "('Alard Briat', Decimal('480.00'))\n",
      "('Basil Slarke', Decimal('139.70'))\n",
      "('Felita Dovey', Decimal('216.14'))\n",
      "('Shanan Mingay', Decimal('78.12'))\n",
      "('Isac Crimpe', Decimal('147.00'))\n",
      "('Elladine Kobiela', Decimal('186.93'))\n",
      "('Rhody Dobbin', Decimal('179.70'))\n",
      "('Mady McMennum', Decimal('216.14'))\n",
      "('Melisse Southeran', Decimal('337.50'))\n",
      "('Charita Bosworth', Decimal('152.40'))\n",
      "('Audie Willcocks', Decimal('337.50'))\n",
      "('Ulick Tebboth', Decimal('179.70'))\n",
      "('Anders Stowe', Decimal('330.00'))\n",
      "('Prudence Eastlake', Decimal('199.76'))\n",
      "('Elayne Karet', Decimal('78.12'))\n",
      "('Carlye Chiswell', Decimal('179.70'))\n",
      "('Hermione Crix', Decimal('78.12'))\n",
      "('Karoline Pocock', Decimal('216.14'))\n",
      "('Pail Duignan', Decimal('125.99'))\n",
      "('Vivie Twinning', Decimal('147.00'))\n",
      "('Anjela Shobrook', Decimal('480.00'))\n",
      "('Artair Lant', Decimal('66.86'))\n",
      "('Charline Warriner', Decimal('352.50'))\n",
      "('Francis Runciman', Decimal('78.12'))\n",
      "('Asia McNess', Decimal('147.00'))\n",
      "('Shell Oldis', Decimal('137.76'))\n",
      "('Gay Skechley', Decimal('186.93'))\n",
      "(\"Harriett O'Sirin\", Decimal('66.86'))\n",
      "('Maighdiln Lamswood', Decimal('199.76'))\n",
      "('Carree Jeffree', Decimal('66.86'))\n",
      "('Berte Tootin', Decimal('66.86'))\n",
      "('Madelin Giacomi', Decimal('480.00'))\n",
      "('Aldric Jerman', Decimal('179.70'))\n",
      "('Donni Tatem', Decimal('137.76'))\n",
      "('Silva Addy', Decimal('330.00'))\n",
      "('Lynsey Ludlamme', Decimal('216.14'))\n",
      "('Garek Gearty', Decimal('104.07'))\n",
      "('Igor Durrand', Decimal('315.00'))\n",
      "('Jethro Fenwick', Decimal('139.70'))\n",
      "('Harlie Jindracek', Decimal('285.00'))\n",
      "('Roxine Humphries', Decimal('285.00'))\n",
      "('Alister Stronack', Decimal('285.00'))\n",
      "('Hebert Aubin', Decimal('315.00'))\n",
      "('Fax Rojahn', Decimal('187.50'))\n",
      "('Merlina Lermit', Decimal('352.50'))\n",
      "('Dre Danher', Decimal('199.76'))\n",
      "('Beryl Coo', Decimal('330.00'))\n",
      "('Roi Critzen', Decimal('352.50'))\n",
      "('Willa Wethered', Decimal('352.50'))\n",
      "('Launce Sowerbutts', Decimal('187.50'))\n",
      "('Grenville Penburton', Decimal('352.50'))\n",
      "('Mona Rudwell', Decimal('137.76'))\n",
      "('Ashil Brogini', Decimal('152.40'))\n",
      "('Adiana Shirtliff', Decimal('125.99'))\n",
      "('Evangeline Bernet', Decimal('139.70'))\n",
      "('Pete Morden', Decimal('125.99'))\n",
      "('Aaron Cromley', Decimal('337.50'))\n",
      "('Dusty Yedall', Decimal('352.50'))\n",
      "('Lana Boyne', Decimal('352.50'))\n",
      "('Dore Coyett', Decimal('186.93'))\n",
      "('Reg Lepper', Decimal('137.76'))\n",
      "('Anastasia Baudy', Decimal('139.70'))\n",
      "('Shandy Sefton', Decimal('465.00'))\n",
      "('Melisandra Mungham', Decimal('137.76'))\n",
      "('Josiah Thayre', Decimal('199.76'))\n",
      "('Julie Brandes', Decimal('465.00'))\n",
      "('Cullie McBrady', Decimal('480.00'))\n",
      "('Quinn Stamps', Decimal('125.99'))\n",
      "('Sabina Corneille', Decimal('480.00'))\n",
      "('Karoly Ivie', Decimal('252.41'))\n",
      "('Haskel Bowell', Decimal('137.76'))\n",
      "('Erika Greensmith', Decimal('137.76'))\n",
      "('Phil Schapero', Decimal('187.50'))\n",
      "('Staci Coppens', Decimal('285.00'))\n",
      "('Valerye Phorsby', Decimal('186.93'))\n",
      "('Zena Todari', Decimal('179.70'))\n",
      "('Gordan Hitscher', Decimal('147.00'))\n",
      "('Rowan Grover', Decimal('199.76'))\n",
      "('Alexia Candelin', Decimal('480.00'))\n",
      "('Giacopo Bramich', Decimal('352.50'))\n",
      "('King Hillin', Decimal('104.07'))\n",
      "('Cirillo Creamen', Decimal('139.70'))\n",
      "('Christoper Myrkus', Decimal('187.50'))\n",
      "('Gale Reeves', Decimal('66.86'))\n",
      "('Eba Harriagn', Decimal('139.70'))\n",
      "('Aldin Purrier', Decimal('465.00'))\n",
      "('Garvin Guerrazzi', Decimal('330.00'))\n",
      "('Winn Raynes', Decimal('104.07'))\n",
      "('Windham Meekin', Decimal('66.86'))\n",
      "(\"Douglas O' Cloney\", Decimal('252.41'))\n",
      "('Bianka McLanaghan', Decimal('315.00'))\n",
      "('Ravid Josephsen', Decimal('252.41'))\n",
      "('Martainn Van Zon', Decimal('252.41'))\n",
      "('Bradford Rafe', Decimal('480.00'))\n",
      "('Kelsy Schroder', Decimal('147.00'))\n",
      "('Lia Bonar', Decimal('112.50'))\n",
      "('Kalinda Grestye', Decimal('137.76'))\n",
      "('Fredelia Snedden', Decimal('139.70'))\n",
      "('Dell Hellsdon', Decimal('125.99'))\n",
      "('Bree Bleas', Decimal('139.70'))\n",
      "('Berte Cornall', Decimal('125.99'))\n",
      "('Gualterio Backshall', Decimal('179.70'))\n",
      "('Marillin Dennehy', Decimal('139.70'))\n",
      "('Annaliese Cowill', Decimal('139.70'))\n",
      "('Mary Demangel', Decimal('352.50'))\n",
      "('Kelbee Illesley', Decimal('252.41'))\n",
      "('Arlette Magauran', Decimal('465.00'))\n",
      "('Marchelle Annes', Decimal('112.50'))\n",
      "('Yorgo Muzzillo', Decimal('112.50'))\n",
      "('Carolan Di Giacomo', Decimal('112.50'))\n",
      "('Reilly Domonkos', Decimal('187.50'))\n",
      "('Richie Brydson', Decimal('216.14'))\n",
      "('Verene Beatens', Decimal('252.41'))\n",
      "('Mei Scrogges', Decimal('147.00'))\n",
      "('Gus Trower', Decimal('330.00'))\n",
      "('Marcelia Kerswell', Decimal('137.76'))\n",
      "('Hanni Dunbleton', Decimal('112.50'))\n",
      "('Sarah Plaschke', Decimal('480.00'))\n",
      "('Renato Paulin', Decimal('480.00'))\n",
      "('Essy Licence', Decimal('137.76'))\n",
      "('Roxana Dicte', Decimal('186.93'))\n",
      "('Ash Boise', Decimal('147.00'))\n",
      "('Chloette Pyke', Decimal('147.00'))\n",
      "('Angel Veschambre', Decimal('315.00'))\n",
      "('Devonne Whal', Decimal('104.07'))\n",
      "('Row Colchett', Decimal('465.00'))\n",
      "('Nels Ordish', Decimal('480.00'))\n",
      "('Brendin Meedendorpe', Decimal('187.50'))\n",
      "('Allyce Mantione', Decimal('152.40'))\n",
      "(\"Jill O'Sirin\", Decimal('187.50'))\n",
      "('Zita Coldbath', Decimal('78.12'))\n",
      "('Darby McLae', Decimal('112.50'))\n",
      "('Killy Condie', Decimal('179.70'))\n",
      "('Cyndi Ruler', Decimal('337.50'))\n",
      "('Leanna Chapelhow', Decimal('78.12'))\n",
      "('Mattie Winyard', Decimal('315.00'))\n",
      "('Alli Cunney', Decimal('186.93'))\n",
      "('Armstrong Collerd', Decimal('216.14'))\n",
      "('Lauri Hughill', Decimal('330.00'))\n",
      "('Nels Hargreaves', Decimal('125.99'))\n",
      "('Elliott Avard', Decimal('465.00'))\n",
      "('Sterne Salterne', Decimal('285.00'))\n",
      "('Christian Yeld', Decimal('330.00'))\n",
      "('Erv Padrick', Decimal('147.00'))\n",
      "('Tamarah Filasov', Decimal('104.07'))\n",
      "('Katherine Midson', Decimal('104.07'))\n",
      "('Belle Priver', Decimal('186.93'))\n",
      "('Inez Flade', Decimal('125.99'))\n",
      "('Berny Elcoate', Decimal('112.50'))\n",
      "('Jillene Maro', Decimal('78.12'))\n",
      "('Julietta Legerwood', Decimal('66.86'))\n",
      "('Anastasie Jahnisch', Decimal('179.70'))\n",
      "('Wynnie Feronet', Decimal('187.50'))\n",
      "('Mirilla Barff', Decimal('139.70'))\n",
      "('Neely Frankcomb', Decimal('465.00'))\n",
      "('Laverna Skeermer', Decimal('125.99'))\n",
      "('Carol-jean Sodory', Decimal('125.99'))\n",
      "('Donella Tomasini', Decimal('216.14'))\n",
      "('Margarette Hobell', Decimal('104.07'))\n",
      "('Fred Tatersale', Decimal('465.00'))\n",
      "('Estele Schultze', Decimal('285.00'))\n",
      "('Celle Oller', Decimal('112.50'))\n",
      "('Ximenes Carnachen', Decimal('285.00'))\n",
      "('Laina Thurborn', Decimal('66.86'))\n",
      "('Kaleena Philips', Decimal('152.40'))\n",
      "('Maisie Matyushkin', Decimal('216.14'))\n",
      "('Merill Leyninye', Decimal('252.41'))\n",
      "('Ara McWard', Decimal('104.07'))\n",
      "('Jefferson Lauderdale', Decimal('104.07'))\n",
      "('Claybourne Costin', Decimal('66.86'))\n",
      "('Marketa Olman', Decimal('465.00'))\n",
      "('Egbert Mollnar', Decimal('187.50'))\n",
      "('Crysta Garratty', Decimal('337.50'))\n",
      "('Emmalynne Hairs', Decimal('112.50'))\n",
      "('Farrel Teare', Decimal('179.70'))\n",
      "('Phillis Denley', Decimal('125.99'))\n",
      "('Petronille Scrimgeour', Decimal('285.00'))\n",
      "('Ernestine Merrgen', Decimal('78.12'))\n",
      "('Alaric Thaw', Decimal('125.99'))\n",
      "('Burke Jupp', Decimal('104.07'))\n",
      "('Caterina Sweetnam', Decimal('139.70'))\n",
      "('Julianna Jostan', Decimal('187.50'))\n",
      "('Kipp Coulling', Decimal('137.76'))\n",
      "('Sandy Rubinowicz', Decimal('147.00'))\n",
      "('Isidro Chelam', Decimal('465.00'))\n",
      "(\"Rodrigo D'Alessio\", Decimal('186.93'))\n",
      "('Onfroi Kornyakov', Decimal('147.00'))\n",
      "('Emera Whitewood', Decimal('465.00'))\n",
      "('Melessa Lecordier', Decimal('330.00'))\n",
      "('Doreen Sothcott', Decimal('480.00'))\n",
      "('Amandie Rohmer', Decimal('285.00'))\n",
      "('Ferdinand Fowley', Decimal('315.00'))\n",
      "('Dinny Fonzone', Decimal('337.50'))\n",
      "('Dian Collough', Decimal('199.76'))\n",
      "('Rayner Lukianovich', Decimal('186.93'))\n",
      "('Purcell Eyer', Decimal('186.93'))\n",
      "('Eleonore Stitcher', Decimal('337.50'))\n",
      "('Mariel Bourdel', Decimal('252.41'))\n",
      "('Hersh Bolgar', Decimal('315.00'))\n",
      "('Rivi Bowart', Decimal('104.07'))\n",
      "('Ash Lodford', Decimal('112.50'))\n",
      "('Emilee Riddeough', Decimal('337.50'))\n",
      "('Gothart Domesday', Decimal('216.14'))\n",
      "('Red Nordass', Decimal('337.50'))\n",
      "('Aubine Chardin', Decimal('252.41'))\n",
      "('Carney Speer', Decimal('152.40'))\n",
      "('Nancy Rollinshaw', Decimal('147.00'))\n",
      "('Seamus Hearl', Decimal('352.50'))\n",
      "('Dwain Eccott', Decimal('152.40'))\n",
      "('Perrine Scalera', Decimal('78.12'))\n",
      "('Esdras Scoffins', Decimal('285.00'))\n",
      "('Adamo Rumens', Decimal('285.00'))\n",
      "('Sander Maloney', Decimal('337.50'))\n",
      "('Ibrahim Jurries', Decimal('330.00'))\n",
      "('Amandi McConaghy', Decimal('186.93'))\n",
      "('Beth Crocket', Decimal('147.00'))\n",
      "('Polly Murton', Decimal('125.99'))\n",
      "('Celine Coopland', Decimal('186.93'))\n",
      "('Renard Crispin', Decimal('125.99'))\n",
      "('Viviyan Lantiff', Decimal('252.41'))\n",
      "('Ferrel Jeratt', Decimal('147.00'))\n",
      "('Ginelle Finnimore', Decimal('352.50'))\n",
      "('Berenice Marples', Decimal('465.00'))\n",
      "('Griz Tawse', Decimal('216.14'))\n",
      "('Rafferty Guyonneau', Decimal('137.76'))\n",
      "('Hamnet Coultas', Decimal('285.00'))\n",
      "('Hale Danilchik', Decimal('285.00'))\n",
      "('Selia Grigoroni', Decimal('252.41'))\n",
      "('Marice Leavens', Decimal('199.76'))\n",
      "('Anabelle Dominelli', Decimal('352.50'))\n",
      "('Adah Adamczewski', Decimal('285.00'))\n",
      "('Baldwin Colchett', Decimal('66.86'))\n",
      "('Claire Morland', Decimal('330.00'))\n",
      "('Fredi Helks', Decimal('125.99'))\n",
      "('Fairfax Seniour', Decimal('139.70'))\n",
      "('Patrizia Kunrad', Decimal('147.00'))\n",
      "('Andrej Wolfindale', Decimal('285.00'))\n",
      "('Lorne Boldry', Decimal('78.12'))\n",
      "('Charline Windrus', Decimal('147.00'))\n",
      "('Kerri Barnes', Decimal('252.41'))\n",
      "('Brunhilda Beeze', Decimal('352.50'))\n",
      "('Sheilah Maestro', Decimal('465.00'))\n",
      "('Linus Gresham', Decimal('104.07'))\n",
      "('Chastity Medlar', Decimal('337.50'))\n",
      "('Kissie Gosford', Decimal('104.07'))\n",
      "('Tommi Durham', Decimal('352.50'))\n",
      "('Lucretia Whyborn', Decimal('337.50'))\n",
      "('Eimile Matz', Decimal('252.41'))\n",
      "('Janeva Buist', Decimal('199.76'))\n",
      "('Winnah Laye', Decimal('330.00'))\n",
      "('Dolorita Drayton', Decimal('337.50'))\n",
      "('Debbi Gaule', Decimal('125.99'))\n",
      "('Flynn Magnay', Decimal('252.41'))\n",
      "('Agnes Acey', Decimal('352.50'))\n",
      "('Lenore Tabb', Decimal('330.00'))\n",
      "('Rorie Colicot', Decimal('199.76'))\n",
      "('Read Trusty', Decimal('147.00'))\n",
      "('Valida Greenhill', Decimal('352.50'))\n",
      "('Emelda Furbank', Decimal('252.41'))\n",
      "('Hilary Pudner', Decimal('139.70'))\n",
      "('Les Harmson', Decimal('147.00'))\n",
      "('Tony Crabtree', Decimal('125.99'))\n",
      "('Mitzi De Mico', Decimal('152.40'))\n",
      "('Des Covet', Decimal('337.50'))\n",
      "('Montgomery Spileman', Decimal('285.00'))\n",
      "('Klement Brothwell', Decimal('337.50'))\n",
      "('Rooney Milbourne', Decimal('315.00'))\n",
      "('Jameson Yaknov', Decimal('337.50'))\n",
      "('Ber Dillet', Decimal('147.00'))\n",
      "('Tove Jaquest', Decimal('199.76'))\n",
      "('Hyacintha Hanne', Decimal('147.00'))\n",
      "('Sabra Corry', Decimal('285.00'))\n",
      "('Pincas Stearn', Decimal('78.12'))\n",
      "('Josephine Archer', Decimal('465.00'))\n",
      "('Enid Francescuccio', Decimal('252.41'))\n",
      "('Manolo Russ', Decimal('112.50'))\n",
      "('Brittni Nielson', Decimal('199.76'))\n",
      "('Gennifer Koenen', Decimal('186.93'))\n",
      "('Marlo McGeaney', Decimal('66.86'))\n",
      "('Wenona MacGinlay', Decimal('199.76'))\n",
      "('Henryetta Kunes', Decimal('337.50'))\n",
      "('Adelheid Casolla', Decimal('252.41'))\n",
      "('Terrye Littlechild', Decimal('330.00'))\n",
      "('Mack Fabri', Decimal('315.00'))\n",
      "('Giselle Abrahart', Decimal('78.12'))\n",
      "('Hynda Skeel', Decimal('315.00'))\n",
      "('Mattie Brenston', Decimal('252.41'))\n",
      "('Codee Pindar', Decimal('315.00'))\n",
      "('Dyanne Labbet', Decimal('152.40'))\n",
      "('Del Hughman', Decimal('199.76'))\n",
      "('Ram Chaudhry', Decimal('480.00'))\n",
      "('Danyelle Butts', Decimal('137.76'))\n",
      "('Yorgos BoHlingolsen', Decimal('285.00'))\n",
      "('Davita Baynham', Decimal('315.00'))\n",
      "('Tamma Clink', Decimal('352.50'))\n",
      "('Leonard Fuxman', Decimal('480.00'))\n",
      "('Britta Barday', Decimal('199.76'))\n",
      "('Nita Vannacci', Decimal('330.00'))\n",
      "('Adria Heller', Decimal('285.00'))\n",
      "('Henry Reaney', Decimal('480.00'))\n",
      "('Abigail Struis', Decimal('152.40'))\n",
      "('Deck Paulat', Decimal('186.93'))\n",
      "('Ephrem Steers', Decimal('216.14'))\n",
      "('Alexandros Brookfield', Decimal('125.99'))\n",
      "('Ennis Dungate', Decimal('66.86'))\n",
      "('Kristian Beeken', Decimal('285.00'))\n",
      "('Zach Bondley', Decimal('125.99'))\n",
      "('Manuel Gloyens', Decimal('285.00'))\n",
      "('Linus Greer', Decimal('465.00'))\n",
      "('Dannye Passmore', Decimal('139.70'))\n",
      "('Tasia Fautly', Decimal('480.00'))\n",
      "('Torr Windrus', Decimal('337.50'))\n",
      "('Leanna Dur', Decimal('315.00'))\n",
      "('Rene Garn', Decimal('352.50'))\n",
      "('Dieter Crannis', Decimal('147.00'))\n",
      "('Paddie Tellenbrok', Decimal('78.12'))\n",
      "('Viva Foulstone', Decimal('199.76'))\n",
      "(\"Jo O'Nowlan\", Decimal('199.76'))\n",
      "('Kristoffer Pales', Decimal('465.00'))\n",
      "('Tera Stockdale', Decimal('152.40'))\n",
      "('Mano Abrahamson', Decimal('480.00'))\n",
      "('Sinclare Milburne', Decimal('152.40'))\n",
      "('Becki Bonsall', Decimal('199.76'))\n",
      "('Aldrich Phythien', Decimal('78.12'))\n",
      "('Adria Koubu', Decimal('152.40'))\n",
      "('Dru Priscott', Decimal('66.86'))\n",
      "('Sid Oultram', Decimal('285.00'))\n",
      "('Steven Cornbell', Decimal('315.00'))\n",
      "('Mariquilla Labbe', Decimal('337.50'))\n",
      "('Arthur Mathewson', Decimal('139.70'))\n",
      "('Christi Flute', Decimal('465.00'))\n",
      "('Sullivan Eddoes', Decimal('125.99'))\n",
      "('Lisle Scamadin', Decimal('216.14'))\n",
      "('Kim McCloughlin', Decimal('315.00'))\n",
      "('Cissiee Gobeau', Decimal('186.93'))\n",
      "('Sibley Rodder', Decimal('152.40'))\n",
      "('Elfrieda Umbers', Decimal('216.14'))\n",
      "('Sabra Calbreath', Decimal('352.50'))\n",
      "('Gearard Rowston', Decimal('104.07'))\n",
      "('Demetris McGibbon', Decimal('480.00'))\n",
      "('Ethelbert Cordeux', Decimal('78.12'))\n",
      "('Audra Hebborn', Decimal('152.40'))\n",
      "('Henrie Karolovsky', Decimal('139.70'))\n",
      "('Cate Pagitt', Decimal('125.99'))\n",
      "('Lise Fegan', Decimal('199.76'))\n",
      "('Persis Chipchase', Decimal('330.00'))\n",
      "('Burgess Hancill', Decimal('137.76'))\n",
      "('Olive Jeannon', Decimal('186.93'))\n",
      "('Steward Doyland', Decimal('352.50'))\n",
      "('Phillipe Ropartz', Decimal('147.00'))\n",
      "('Brit Northfield', Decimal('139.70'))\n",
      "('Melicent Gieves', Decimal('337.50'))\n",
      "('Sheffield Turbitt', Decimal('315.00'))\n",
      "('Bonnee Keller', Decimal('216.14'))\n",
      "('Alexandr McGill', Decimal('78.12'))\n",
      "('Kali Avis', Decimal('137.76'))\n",
      "('Vania Gilding', Decimal('66.86'))\n",
      "('Leonie Battin', Decimal('179.70'))\n",
      "('Sherye Christmas', Decimal('216.14'))\n",
      "('Janith Bowra', Decimal('66.86'))\n",
      "('Malinde Blunn', Decimal('139.70'))\n",
      "('Sophey Garling', Decimal('285.00'))\n",
      "('Delilah Ayerst', Decimal('480.00'))\n",
      "('Payton Rissen', Decimal('147.00'))\n",
      "('Elisabetta Dubery', Decimal('137.76'))\n",
      "('Gabrielle Coxall', Decimal('137.76'))\n",
      "('Cissy Blondelle', Decimal('179.70'))\n",
      "('Maddalena Wolfinger', Decimal('465.00'))\n",
      "('Jerrie Jiran', Decimal('125.99'))\n",
      "('Hilly Leahey', Decimal('152.40'))\n",
      "('Ardenia Lobb', Decimal('104.07'))\n",
      "('Johnette Haitlie', Decimal('104.07'))\n",
      "('Shannon Osban', Decimal('480.00'))\n",
      "('Deina Agus', Decimal('78.12'))\n",
      "('Dene Dawby', Decimal('78.12'))\n",
      "('Bentley Gwyneth', Decimal('137.76'))\n",
      "('Quintus Parcells', Decimal('186.93'))\n",
      "('Jessalin Dimitriades', Decimal('125.99'))\n",
      "('Gordan Kneeshaw', Decimal('78.12'))\n",
      "('Wilek Ivanyushkin', Decimal('66.86'))\n",
      "('Lowrance Kleinmintz', Decimal('252.41'))\n",
      "('Cornall Pimlock', Decimal('337.50'))\n",
      "('Kathy Fairlam', Decimal('187.50'))\n",
      "('Doll Friary', Decimal('187.50'))\n",
      "('Cornela LaBastida', Decimal('216.14'))\n",
      "('Fanni Caccavella', Decimal('104.07'))\n",
      "('Anny Pattemore', Decimal('285.00'))\n",
      "('Raye Rossant', Decimal('465.00'))\n",
      "('Licha Verden', Decimal('187.50'))\n",
      "('Lauralee Beteriss', Decimal('285.00'))\n",
      "('Riley Curnnok', Decimal('186.93'))\n",
      "('Candy Simoncelli', Decimal('216.14'))\n",
      "('Vale Norwood', Decimal('252.41'))\n",
      "('Sly Fullwood', Decimal('139.70'))\n",
      "('Hall Everil', Decimal('152.40'))\n",
      "('Webster Lomax', Decimal('252.41'))\n",
      "('Jacynth Clubb', Decimal('285.00'))\n",
      "('Cathe Snar', Decimal('137.76'))\n",
      "('Katrina Aylett', Decimal('104.07'))\n",
      "('Monique Fry', Decimal('125.99'))\n",
      "('Jacquetta Plampin', Decimal('187.50'))\n",
      "('Ellis Castanares', Decimal('147.00'))\n",
      "('Nadine Cudbird', Decimal('187.50'))\n",
      "('Jaynell Alty', Decimal('112.50'))\n",
      "('Skipp Lowater', Decimal('315.00'))\n",
      "('Cori Percifer', Decimal('465.00'))\n",
      "('Tiler Kenrack', Decimal('330.00'))\n",
      "('Willow Burmingham', Decimal('139.70'))\n",
      "('Allyn Gurnay', Decimal('315.00'))\n",
      "('Lucho McGerraghty', Decimal('216.14'))\n",
      "('Jemmy Whelan', Decimal('125.99'))\n",
      "('Ellis Kops', Decimal('285.00'))\n",
      "('Marsiella Duprey', Decimal('480.00'))\n",
      "('Kimberli Eisenberg', Decimal('186.93'))\n",
      "('Serena Yerby', Decimal('112.50'))\n",
      "('Paxon Jeffcoat', Decimal('66.86'))\n",
      "('Rici Bollin', Decimal('112.50'))\n",
      "('Alisander Shoebottom', Decimal('330.00'))\n",
      "('Lance Cheatle', Decimal('179.70'))\n",
      "('Marsh Fransoni', Decimal('186.93'))\n",
      "('Alisander Cornelisse', Decimal('179.70'))\n",
      "('Rania Gerritsma', Decimal('152.40'))\n",
      "('Howie Flamank', Decimal('352.50'))\n",
      "('Mariann Ibbeson', Decimal('78.12'))\n",
      "('Lilian Dislee', Decimal('179.70'))\n",
      "('Ainslee Feighney', Decimal('112.50'))\n",
      "('Nessie Wheal', Decimal('352.50'))\n",
      "('Titos Edgcumbe', Decimal('78.12'))\n",
      "('Barby Noell', Decimal('315.00'))\n",
      "('Gilberta Sabberton', Decimal('125.99'))\n",
      "('Hervey Ganning', Decimal('199.76'))\n",
      "('Adlai Arnull', Decimal('337.50'))\n",
      "('Christoforo Vagg', Decimal('139.70'))\n",
      "('Malinde Firbanks', Decimal('112.50'))\n",
      "('Virgie Belhomme', Decimal('187.50'))\n",
      "('Madlin McGrory', Decimal('112.50'))\n",
      "('Jolee Linthead', Decimal('152.40'))\n",
      "('Todd Riglesford', Decimal('78.12'))\n",
      "('Clarette Barreau', Decimal('330.00'))\n",
      "('Leone Klulisek', Decimal('352.50'))\n",
      "('Sharai MacMenamin', Decimal('285.00'))\n",
      "('Zebedee Spafford', Decimal('199.76'))\n",
      "('Lucais Sewards', Decimal('252.41'))\n",
      "('Merrill Sawford', Decimal('179.70'))\n",
      "('Felix Ouver', Decimal('179.70'))\n",
      "('Rana Rait', Decimal('137.76'))\n",
      "('Chrotoem Harniman', Decimal('187.50'))\n",
      "('Joye MacHostie', Decimal('186.93'))\n",
      "('Rayna Strathearn', Decimal('179.70'))\n",
      "('Mellicent Philliphs', Decimal('139.70'))\n",
      "('Natka Featenby', Decimal('152.40'))\n",
      "('Ariadne Copeland', Decimal('187.50'))\n",
      "('Ferguson Wilcocke', Decimal('252.41'))\n",
      "('Yardley Eliet', Decimal('315.00'))\n",
      "('Raven Cawkwell', Decimal('104.07'))\n"
     ]
    }
   ],
   "source": [
    "query = \"\"\"\n",
    "SELECT \n",
    "    CustomerDetails.Name AS CustomerName,\n",
    "    Orders.TotalPrice AS OrderTotal\n",
    "FROM \n",
    "    CustomerDetails\n",
    "INNER JOIN \n",
    "    Orders \n",
    "ON \n",
    "    CustomerDetails.CustomerID = Orders.CustomerID\n",
    "WHERE \n",
    "    Orders.TotalPrice > 60;\n",
    "\"\"\"\n",
    "\n",
    "cursor.execute(query)\n",
    "results = cursor.fetchall()\n",
    "\n",
    "for row in results:\n",
    "    print(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd3ff065-945f-4bf3-85b8-4959f286ccfe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
