{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "62de0405-548a-42ab-a35f-5860503aff95",
   "metadata": {},
   "outputs": [],
   "source": [
    "import mysql.connector as connector"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "52c5cc67-206a-4e31-b43c-4a9346a0e576",
   "metadata": {},
   "outputs": [],
   "source": [
    "connection = connector.connect(\n",
    "    user=\"dbcourse\",\n",
    "    password=\"DBc0urse123!!!\",\n",
    "    host=\"localhost\",\n",
    "    database=\"LittleLemonDM\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9824d237-91f3-4ba6-8e9a-b9bf4acedcb6",
   "metadata": {},
   "outputs": [],
   "source": [
    "cursor = connection.cursor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0ed4e342-7c3b-42b5-9183-05cc4b92693c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Bookings',)\n",
      "('CustomerDetails',)\n",
      "('MenuItems',)\n",
      "('OrderDeliveryStatus',)\n",
      "('OrderMenuItems',)\n",
      "('Orders',)\n",
      "('ordersview',)\n",
      "('StaffInfo',)\n"
     ]
    }
   ],
   "source": [
    "cursor.execute(\"SHOW TABLES;\")\n",
    "results = cursor.fetchall()\n",
    "\n",
    "for table in results:\n",
    "    print(table)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "82f52dbf-70a9-48da-bd2c-b6e21800d211",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "query = \"\"\"\n",
    "SELECT \n",
    "    CustomerDetails.Name AS CustomerName,\n",
    "    CustomerDetails.ContactNumber AS ContactNumber,\n",
    "    Orders.TotalPrice AS OrderTotal\n",
    "FROM \n",
    "    CustomerDetails\n",
    "INNER JOIN \n",
    "    Orders \n",
    "ON \n",
    "    CustomerDetails.CustomerID = Orders.CustomerID\n",
    "WHERE \n",
    "    Orders.TotalPrice > 60;\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "dd3ff065-945f-4bf3-85b8-4959f286ccfe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Pansie Alldis', '555-1234', Decimal('465.00'))\n",
      "('Xymenes Hands', '555-1235', Decimal('104.07'))\n",
      "('Lulu Hastin', '555-1236', Decimal('125.99'))\n",
      "('Salvidor Francesch', '555-1237', Decimal('337.50'))\n",
      "('Noni Quickenden', '555-1238', Decimal('465.00'))\n",
      "('Jilleen Foux', '555-1239', Decimal('125.99'))\n",
      "('Grenville Hyne', '555-1242', Decimal('285.00'))\n",
      "('Ram Sinclaire', '555-1241', Decimal('152.40'))\n",
      "('Jilly Bursnoll', 'China', Decimal('199.76'))\n",
      "('Gabe Boyan', '555-1243', Decimal('252.41'))\n",
      "('Anna-maria Neilan', '555-1244', Decimal('66.86'))\n",
      "('Gage Tocknell', '555-1245', Decimal('112.50'))\n",
      "('Dennie Lilloe', '555-1246', Decimal('137.76'))\n",
      "('Harriott Manby', '555-1247', Decimal('125.99'))\n",
      "('Cyril Copelli', '555-1248', Decimal('285.00'))\n",
      "('Fidelity Banham', '555-1249', Decimal('480.00'))\n",
      "('Anna-diane Kopps', '555-1250', Decimal('78.12'))\n",
      "('Raquel Borham', '555-1251', Decimal('352.50'))\n",
      "('Alan Paskell', 'China', Decimal('337.50'))\n",
      "('Pierson Baal', 'China', Decimal('112.50'))\n",
      "('Darla Kubacek', 'Indonesia', Decimal('78.12'))\n",
      "('Eva Dulake', 'France', Decimal('187.50'))\n",
      "('Christabella Coathup', 'Indonesia', Decimal('186.93'))\n",
      "('Karlene Whetson', 'Mali', Decimal('352.50'))\n",
      "('Everard Trasler', 'Thailand', Decimal('465.00'))\n",
      "('Paloma Spellar', 'Colombia', Decimal('285.00'))\n",
      "('Maryjo Strangwood', 'Poland', Decimal('216.14'))\n",
      "('Deane Benbough', 'China', Decimal('337.50'))\n",
      "('Pablo Dracksford', 'Trinidad and Tobago', Decimal('465.00'))\n",
      "('Durand Kitt', 'Russia', Decimal('137.76'))\n",
      "('Jessey Doddrell', 'Slovenia', Decimal('330.00'))\n",
      "('Jacky Shapero', 'Bermuda', Decimal('285.00'))\n",
      "('Laurianne Diehn', 'Madagascar', Decimal('330.00'))\n",
      "('Gauthier Sapshed', 'Pakistan', Decimal('112.50'))\n",
      "('Westbrooke Blindt', 'Israel', Decimal('187.50'))\n",
      "('Sherilyn Ilewicz', 'Philippines', Decimal('78.12'))\n",
      "('Annaliese Brunsden', 'Germany', Decimal('330.00'))\n",
      "('Fawnia Bartosch', 'Nepal', Decimal('66.86'))\n",
      "('Damiano Yurasov', 'Philippines', Decimal('465.00'))\n",
      "('Megan Beddows', 'Argentina', Decimal('352.50'))\n",
      "('Jerome Ovitts', 'Guatemala', Decimal('139.70'))\n",
      "('Freida Nannizzi', 'Ukraine', Decimal('179.70'))\n",
      "('Obidiah Zanicchi', 'Indonesia', Decimal('112.50'))\n",
      "('Aime Ferry', 'United States', Decimal('137.76'))\n",
      "('Dareen Soutar', 'Japan', Decimal('216.14'))\n",
      "('Stan Clethro', 'Russia', Decimal('252.41'))\n",
      "('Sol Hynam', 'Sweden', Decimal('337.50'))\n",
      "('Maribelle Allcroft', 'Peru', Decimal('352.50'))\n",
      "('Nerty Green', 'China', Decimal('465.00'))\n",
      "('Roddie Winterbotham', 'Colombia', Decimal('199.76'))\n",
      "('Egon Lawrance', 'Portugal', Decimal('125.99'))\n",
      "('Mirna Rosita', 'Russia', Decimal('330.00'))\n",
      "('Nelli Myrie', 'Poland', Decimal('480.00'))\n",
      "('Constantina Mottley', 'Russia', Decimal('78.12'))\n",
      "('Althea Jaggli', 'Mexico', Decimal('315.00'))\n",
      "('Ginevra Pally', 'Reunion', Decimal('252.41'))\n",
      "('Hedi Pellington', 'Kosovo', Decimal('152.40'))\n",
      "('Rubin Ind', 'Philippines', Decimal('137.76'))\n",
      "('Petronille Southwood', 'Portugal', Decimal('125.99'))\n",
      "('Merwin Pikhno', 'United States', Decimal('187.50'))\n",
      "('Desdemona Dobbinson', 'Ukraine', Decimal('216.14'))\n",
      "('Lucilia Sandeman', 'China', Decimal('352.50'))\n",
      "('Ingamar Forker', 'Luxembourg', Decimal('104.07'))\n",
      "('Hermine Dorton', 'Poland', Decimal('78.12'))\n",
      "('Valma Brideau', 'Russia', Decimal('78.12'))\n",
      "('Marcile Meffen', 'China', Decimal('315.00'))\n",
      "('Katy Pine', 'China', Decimal('465.00'))\n",
      "('Jordan Donner', 'Portugal', Decimal('337.50'))\n",
      "('Forester Buxcey', 'Brazil', Decimal('465.00'))\n",
      "('Ethelind Schnieder', 'Sweden', Decimal('199.76'))\n",
      "('Elsworth Stannas', 'China', Decimal('139.70'))\n",
      "('Tiffani Halstead', 'Russia', Decimal('137.76'))\n",
      "('Aluin McUre', 'Sweden', Decimal('315.00'))\n",
      "('Paulie Lemerle', 'Madagascar', Decimal('104.07'))\n",
      "('Lew Allot', 'Portugal', Decimal('152.40'))\n",
      "('Berne Banbury', 'Russia', Decimal('187.50'))\n",
      "('Chrotoem Estevez', 'Peru', Decimal('315.00'))\n",
      "('Lottie Schultheiss', 'Japan', Decimal('147.00'))\n",
      "('Othella Flood', 'Thailand', Decimal('480.00'))\n",
      "('Giusto Sheavills', 'Ukraine', Decimal('352.50'))\n",
      "('Kelwin Ryle', 'Philippines', Decimal('186.93'))\n",
      "('Jobie Coaten', 'Chile', Decimal('199.76'))\n",
      "('Gianni Aistrop', 'Colombia', Decimal('315.00'))\n",
      "('Virginie McGrey', 'Malaysia', Decimal('216.14'))\n",
      "('Bertrand Bilton', 'Argentina', Decimal('465.00'))\n",
      "('Natasha Cool', 'Netherlands', Decimal('337.50'))\n",
      "('Aurie Unthank', 'Mongolia', Decimal('187.50'))\n",
      "('Robbin Shottin', 'China', Decimal('199.76'))\n",
      "('Ally McBrearty', 'France', Decimal('216.14'))\n",
      "('Boot Burree', 'China', Decimal('187.50'))\n",
      "('Mignonne Shepland', 'Indonesia', Decimal('337.50'))\n",
      "('Nelie Cleare', 'China', Decimal('152.40'))\n",
      "('Serene Steadman', 'China', Decimal('330.00'))\n",
      "(\"Susette O'Neil\", 'United States', Decimal('480.00'))\n",
      "('Cathleen Gooday', 'Portugal', Decimal('480.00'))\n",
      "('Essie Hagland', 'Russia', Decimal('187.50'))\n",
      "('Annice Maxworthy', 'China', Decimal('186.93'))\n",
      "('Walther Rablin', 'China', Decimal('337.50'))\n",
      "('Alyse Pimlett', 'Poland', Decimal('216.14'))\n",
      "('Dill Beardshall', 'China', Decimal('465.00'))\n",
      "('Hermione Tire', 'Brazil', Decimal('66.86'))\n",
      "(\"Web O'Howbane\", 'Portugal', Decimal('465.00'))\n",
      "('Kimble Wayvill', 'Gambia', Decimal('199.76'))\n",
      "('Steffane Karpol', 'Greece', Decimal('66.86'))\n",
      "('Dominick Crafts', 'Afghanistan', Decimal('330.00'))\n",
      "('Odilia Bockett', 'France', Decimal('104.07'))\n",
      "('Ariadne McCrie', 'Indonesia', Decimal('187.50'))\n",
      "('Theadora Huetson', 'China', Decimal('78.12'))\n",
      "('Herve Tunmore', 'Zimbabwe', Decimal('186.93'))\n",
      "('Marena Jacox', 'France', Decimal('216.14'))\n",
      "('Ali Einchcombe', 'China', Decimal('315.00'))\n",
      "('Ezequiel Benion', 'Jamaica', Decimal('187.50'))\n",
      "('Silas Asson', 'Ukraine', Decimal('352.50'))\n",
      "('Jesse Martelet', 'Russia', Decimal('186.93'))\n",
      "('Lexie Spinetti', 'China', Decimal('152.40'))\n",
      "('Nev Bompas', 'China', Decimal('199.76'))\n",
      "('Weston Dearden', 'China', Decimal('137.76'))\n",
      "('Natty Murt', 'Gambia', Decimal('285.00'))\n",
      "('Kiley Nare', 'Brazil', Decimal('186.93'))\n",
      "('Ondrea Keyser', 'Bosnia and Herzegovina', Decimal('104.07'))\n",
      "('Tabbie Conboy', 'Argentina', Decimal('137.76'))\n",
      "('Schuyler Walewski', 'United States', Decimal('179.70'))\n",
      "('Worth Laweles', 'Ghana', Decimal('465.00'))\n",
      "('Maible Dalgarno', 'China', Decimal('147.00'))\n",
      "('Camille Symmons', 'China', Decimal('112.50'))\n",
      "('Ermina Kitter', 'China', Decimal('147.00'))\n",
      "('Ryley McKillop', 'Thailand', Decimal('252.41'))\n",
      "('Jackelyn Jacox', 'Philippines', Decimal('187.50'))\n",
      "('Dietrich Feetham', 'Mozambique', Decimal('216.14'))\n",
      "('Stewart Keppe', 'Austria', Decimal('330.00'))\n",
      "('Celinda Mamwell', 'Indonesia', Decimal('216.14'))\n",
      "('Philomena Petracchi', 'Russia', Decimal('112.50'))\n",
      "('Rosanne Zorzutti', 'Nigeria', Decimal('152.40'))\n",
      "('Melisent Claessens', 'Vietnam', Decimal('285.00'))\n",
      "('Stirling Santry', 'Bangladesh', Decimal('179.70'))\n",
      "('Orel Gawthrope', 'Egypt', Decimal('139.70'))\n",
      "('Jazmin Torald', 'Portugal', Decimal('152.40'))\n",
      "('Marillin Tieman', 'Japan', Decimal('252.41'))\n",
      "('Jenda Castellino', 'China', Decimal('179.70'))\n",
      "('Itch Merle', 'Sri Lanka', Decimal('137.76'))\n",
      "(\"Goldie O'Sherrin\", 'Portugal', Decimal('315.00'))\n",
      "('Julius Scutchin', 'Philippines', Decimal('199.76'))\n",
      "('Dalila Baldree', 'Pitcairn', Decimal('137.76'))\n",
      "('Steward Pettinger', 'Indonesia', Decimal('480.00'))\n",
      "('Morgan Gouldeby', 'Brazil', Decimal('285.00'))\n",
      "('Melloney Schimke', 'Colombia', Decimal('179.70'))\n",
      "('Magdalen Lacheze', 'China', Decimal('147.00'))\n",
      "('Blancha Trippack', 'Greece', Decimal('216.14'))\n",
      "('Boot Terbeck', 'Poland', Decimal('337.50'))\n",
      "('Tyson Gahagan', 'Malaysia', Decimal('179.70'))\n",
      "('Giffy Wreath', 'Brazil', Decimal('78.12'))\n",
      "('Dulcie Lax', 'Czech Republic', Decimal('330.00'))\n",
      "('Fielding Struys', 'China', Decimal('252.41'))\n",
      "('Wanda Ramas', 'Brazil', Decimal('216.14'))\n",
      "('Gigi Trunchion', 'Russia', Decimal('216.14'))\n",
      "('Waylan Grieve', 'China', Decimal('285.00'))\n",
      "('Almeta Laird-Craig', 'Afghanistan', Decimal('337.50'))\n",
      "('Ezri Gouck', 'Latvia', Decimal('137.76'))\n",
      "('Karia Sonier', 'China', Decimal('66.86'))\n",
      "('Linc Martynov', 'France', Decimal('104.07'))\n",
      "('Evelyn Serrier', 'France', Decimal('186.93'))\n",
      "('Callie Dunning', 'China', Decimal('104.07'))\n",
      "('Rowena Santori', 'Poland', Decimal('179.70'))\n",
      "('Charlot Warkup', 'Indonesia', Decimal('152.40'))\n",
      "('Sherm Probat', 'Ukraine', Decimal('139.70'))\n",
      "('Maddie Raw', 'Russia', Decimal('480.00'))\n",
      "('Cynthy Stovold', 'Hungary', Decimal('66.86'))\n",
      "('Ives Darmody', 'China', Decimal('66.86'))\n",
      "('Natala Stobbe', 'Sweden', Decimal('315.00'))\n",
      "('Beret Behneke', 'Japan', Decimal('216.14'))\n",
      "('Kiersten Dalliwater', 'France', Decimal('330.00'))\n",
      "('Charin Pinckard', 'China', Decimal('216.14'))\n",
      "(\"Melinda O'Brogan\", 'Sweden', Decimal('78.12'))\n",
      "('Clevey Garfit', 'South Korea', Decimal('179.70'))\n",
      "('Renata Vlach', 'Poland', Decimal('337.50'))\n",
      "('Chaddy Mangeney', 'Honduras', Decimal('330.00'))\n",
      "('Devy Hookes', 'China', Decimal('139.70'))\n",
      "('Dniren Copperwaite', 'China', Decimal('139.70'))\n",
      "('Niles MacMenamy', 'China', Decimal('78.12'))\n",
      "('Jackie Kment', 'Vietnam', Decimal('179.70'))\n",
      "('Kariotta Core', 'Nigeria', Decimal('152.40'))\n",
      "('Waldo Tomkiss', 'Portugal', Decimal('199.76'))\n",
      "('Terencio Loche', 'Kenya', Decimal('112.50'))\n",
      "('Sue Fargie', 'Brazil', Decimal('216.14'))\n",
      "('Tiertza Barford', 'Russia', Decimal('480.00'))\n",
      "('Taffy Shipcott', 'Gambia', Decimal('480.00'))\n",
      "('Sibyl Cuphus', 'Nicaragua', Decimal('152.40'))\n",
      "('Bobby Blazewski', 'China', Decimal('187.50'))\n",
      "('Florinda Cellier', 'Poland', Decimal('252.41'))\n",
      "('Reggie Hallaways', 'China', Decimal('66.86'))\n",
      "('Hallie Roddam', 'Indonesia', Decimal('352.50'))\n",
      "('Junie Older', 'Iran', Decimal('465.00'))\n",
      "('Raymond Cranage', 'Indonesia', Decimal('252.41'))\n",
      "('Georgeanna Boulton', 'Russia', Decimal('139.70'))\n",
      "('Porty Auston', 'China', Decimal('66.86'))\n",
      "('Steffie Slemmonds', 'China', Decimal('112.50'))\n",
      "('Ynez Hows', 'Brazil', Decimal('352.50'))\n",
      "('Julina Di Franceschi', 'China', Decimal('337.50'))\n",
      "('Hakeem Leadston', 'China', Decimal('187.50'))\n",
      "('Enrika Marty', 'China', Decimal('152.40'))\n",
      "('Forest Cole', 'Guatemala', Decimal('315.00'))\n",
      "('Gavra Breslin', 'Russia', Decimal('147.00'))\n",
      "('Karee Colchett', 'France', Decimal('216.14'))\n",
      "('Thorin Jolliman', 'China', Decimal('137.76'))\n",
      "('Gizela Northover', 'China', Decimal('330.00'))\n",
      "('Margarita Mancktelow', 'Nigeria', Decimal('252.41'))\n",
      "('Myra Zaczek', 'Argentina', Decimal('330.00'))\n",
      "('Averell Joint', 'China', Decimal('465.00'))\n",
      "('Jonell Aiton', 'Pakistan', Decimal('186.93'))\n",
      "('Allyce Berthon', 'Russia', Decimal('112.50'))\n",
      "('Theda Jagoe', 'Afghanistan', Decimal('152.40'))\n",
      "('Far Emmanuele', 'Sweden', Decimal('137.76'))\n",
      "('Guthry Galpin', 'France', Decimal('285.00'))\n",
      "('Cordelia Whicher', 'France', Decimal('337.50'))\n",
      "('Mickie Alred', 'Japan', Decimal('112.50'))\n",
      "('Cahra Delacoste', 'China', Decimal('66.86'))\n",
      "('Bennett Pendered', 'South Korea', Decimal('78.12'))\n",
      "('Pietra Paute', 'Peru', Decimal('152.40'))\n",
      "('Heida Bohden', 'Russia', Decimal('125.99'))\n",
      "('Anatole Desforges', 'Ghana', Decimal('66.86'))\n",
      "('Kaylyn Colebourne', 'China', Decimal('315.00'))\n",
      "('Yvon Chasmor', 'Argentina', Decimal('330.00'))\n",
      "('Yorgos Staite', 'South Africa', Decimal('112.50'))\n",
      "('Kally Biers', 'Guatemala', Decimal('125.99'))\n",
      "('Alena Geratasch', 'Germany', Decimal('315.00'))\n",
      "('Agretha Dutteridge', 'Namibia', Decimal('285.00'))\n",
      "('Maison Shoreson', 'Panama', Decimal('112.50'))\n",
      "('Barnabas Casson', 'Kenya', Decimal('465.00'))\n",
      "('Araldo Bramhall', 'Canada', Decimal('137.76'))\n",
      "('Noby Torvey', 'Trinidad and Tobago', Decimal('337.50'))\n",
      "('Cornelius Harkess', 'Mexico', Decimal('285.00'))\n",
      "('Calla Lambal', 'Paraguay', Decimal('315.00'))\n",
      "('Peggie Biddles', 'Malaysia', Decimal('252.41'))\n",
      "('Cristabel Nutty', 'China', Decimal('216.14'))\n",
      "('Paco Towersey', 'Russia', Decimal('78.12'))\n",
      "('Koral Stampfer', 'China', Decimal('179.70'))\n",
      "('Nickolai Balmer', 'China', Decimal('285.00'))\n",
      "('Cal Rorke', 'Indonesia', Decimal('139.70'))\n",
      "('Arnie Jay', 'Indonesia', Decimal('315.00'))\n",
      "('Annamarie Taylot', 'Sweden', Decimal('112.50'))\n",
      "('Roosevelt Grigg', 'China', Decimal('112.50'))\n",
      "('Aube Francescuzzi', 'France', Decimal('125.99'))\n",
      "('Dorie Cammell', 'Russia', Decimal('104.07'))\n",
      "('Zora Hanalan', 'Philippines', Decimal('252.41'))\n",
      "('Alfreda Chasmer', 'United States', Decimal('199.76'))\n",
      "('Norby Foord', 'Czech Republic', Decimal('152.40'))\n",
      "('Miquela Dutnell', 'Russia', Decimal('337.50'))\n",
      "('Ulberto Alyutin', 'Brazil', Decimal('216.14'))\n",
      "('Teriann Olivari', 'Canada', Decimal('66.86'))\n",
      "('Tersina Wolfer', 'Iran', Decimal('330.00'))\n",
      "('Mathew Groucutt', 'Nigeria', Decimal('139.70'))\n",
      "('Zorana Diggin', 'China', Decimal('315.00'))\n",
      "('Graham Rumford', 'Azerbaijan', Decimal('152.40'))\n",
      "('Uriel Grooby', 'Japan', Decimal('187.50'))\n",
      "('Heinrick Setchfield', 'China', Decimal('315.00'))\n",
      "('Ezequiel Cunniff', 'Poland', Decimal('125.99'))\n",
      "('Carena Nucator', 'Venezuela', Decimal('139.70'))\n",
      "('Andonis Rawling', 'China', Decimal('480.00'))\n",
      "('Kellina Oates', 'Argentina', Decimal('186.93'))\n",
      "('Sue Voyce', 'China', Decimal('139.70'))\n",
      "('Hulda Nayshe', 'Indonesia', Decimal('66.86'))\n",
      "('Deloria Hannen', 'Uganda', Decimal('186.93'))\n",
      "('Yankee Penright', 'Russia', Decimal('147.00'))\n",
      "('Ansell Lethlay', 'Bangladesh', Decimal('179.70'))\n",
      "('Riordan Wormald', 'Ethiopia', Decimal('330.00'))\n",
      "('Korney Buffery', 'Greece', Decimal('352.50'))\n",
      "('Elora Eliesco', 'Moldova', Decimal('152.40'))\n",
      "('Lenci McFadzean', 'Honduras', Decimal('179.70'))\n",
      "('Hamlen Mashro', 'China', Decimal('186.93'))\n",
      "('Sully Cunney', 'Afghanistan', Decimal('104.07'))\n",
      "('Lind Haggath', 'Argentina', Decimal('465.00'))\n",
      "('Braden Bartolacci', 'France', Decimal('187.50'))\n",
      "('Morganne Brecknell', 'Kyrgyzstan', Decimal('285.00'))\n",
      "('Guthrey Juara', 'Thailand', Decimal('147.00'))\n",
      "('Dacey Witherden', 'Argentina', Decimal('285.00'))\n",
      "('Gail Grigaut', 'Indonesia', Decimal('199.76'))\n",
      "('Bambie Frears', 'China', Decimal('66.86'))\n",
      "('Elke Dumingos', 'China', Decimal('187.50'))\n",
      "('Son Hurworth', 'Brazil', Decimal('147.00'))\n",
      "('Horatio Codi', 'Armenia', Decimal('139.70'))\n",
      "('Ignace Cooney', 'Mexico', Decimal('315.00'))\n",
      "('Carleen Gyver', 'Armenia', Decimal('199.76'))\n",
      "('Rhetta Nevill', 'Philippines', Decimal('330.00'))\n",
      "('Lethia Bodechon', 'Sweden', Decimal('78.12'))\n",
      "('Hastie Charopen', 'Philippines', Decimal('315.00'))\n",
      "('Araldo Gutman', 'China', Decimal('112.50'))\n",
      "('Derry Davis', 'Panama', Decimal('104.07'))\n",
      "('Fayre Crocket', 'Estonia', Decimal('252.41'))\n",
      "('Nathanil Eykel', 'Japan', Decimal('78.12'))\n",
      "('Ely Doodson', 'China', Decimal('78.12'))\n",
      "('Alvan Winspare', 'Kazakhstan', Decimal('199.76'))\n",
      "('Forster Pervew', 'New Zealand', Decimal('315.00'))\n",
      "('Mureil Codman', 'Portugal', Decimal('330.00'))\n",
      "('Grenville Bottomore', 'Tunisia', Decimal('465.00'))\n",
      "('Selena Relton', 'Indonesia', Decimal('179.70'))\n",
      "('Adaline Reichartz', 'China', Decimal('186.93'))\n",
      "('Den Coppock.', 'Canada', Decimal('330.00'))\n",
      "('Olly Dobbinson', 'Albania', Decimal('337.50'))\n",
      "('Gusella Wadeling', 'Indonesia', Decimal('285.00'))\n",
      "('Kalindi Ryman', 'Indonesia', Decimal('137.76'))\n",
      "('Nadean Elves', 'Czech Republic', Decimal('66.86'))\n",
      "('Ham Penhall', 'Uganda', Decimal('186.93'))\n",
      "('Wakefield Strotton', 'Portugal', Decimal('78.12'))\n",
      "('Dominga Mc Kellen', 'Russia', Decimal('66.86'))\n",
      "('Dennison Qusklay', 'France', Decimal('152.40'))\n",
      "('Erinn Vannar', 'France', Decimal('337.50'))\n",
      "('Michaela Babcock', 'Russia', Decimal('179.70'))\n",
      "('Rene Clements', 'Bolivia', Decimal('187.50'))\n",
      "('Evvie Crossby', 'Central African Republic', Decimal('139.70'))\n",
      "('Hedi Chadwin', 'China', Decimal('352.50'))\n",
      "('Zorine Delacourt', 'Albania', Decimal('315.00'))\n",
      "(\"Gradey O'Gready\", 'China', Decimal('147.00'))\n",
      "('Joycelin Loghan', 'China', Decimal('66.86'))\n",
      "('Paton Fritzer', 'Poland', Decimal('147.00'))\n",
      "('Jenilee Ricardou', 'Ukraine', Decimal('112.50'))\n",
      "('Katie Betancourt', 'Moldova', Decimal('152.40'))\n",
      "('Tildy Shanks', 'Philippines', Decimal('112.50'))\n",
      "('Kellyann Sambells', 'Indonesia', Decimal('330.00'))\n",
      "('Godfrey Jellicorse', 'Russia', Decimal('139.70'))\n",
      "('Rudolph Brozek', 'France', Decimal('147.00'))\n",
      "('Adrianne Freeland', 'France', Decimal('186.93'))\n",
      "('Melesa Halahan', 'Mexico', Decimal('152.40'))\n",
      "('Ardene Davydenko', 'Gambia', Decimal('199.76'))\n",
      "('Elvina McGlynn', 'China', Decimal('112.50'))\n",
      "('Haily Izakoff', 'South Africa', Decimal('315.00'))\n",
      "('Currie Fidell', 'Democratic Republic of th', Decimal('337.50'))\n",
      "('Jillayne Gaiford', 'Kazakhstan', Decimal('352.50'))\n",
      "('Hinda Giacopetti', 'France', Decimal('104.07'))\n",
      "('Delly Ventum', 'Thailand', Decimal('252.41'))\n",
      "('Reginauld Kelemen', 'France', Decimal('104.07'))\n",
      "('Barnabas Gerrell', 'Luxembourg', Decimal('125.99'))\n",
      "('Susie Torrisi', 'Russia', Decimal('152.40'))\n",
      "('Curry Able', 'Indonesia', Decimal('315.00'))\n",
      "('Charil Fanton', 'Ireland', Decimal('66.86'))\n",
      "('Colver McChesney', 'Indonesia', Decimal('112.50'))\n",
      "('Tedda Plumridge', 'Croatia', Decimal('216.14'))\n",
      "('Sandor Barradell', 'Indonesia', Decimal('104.07'))\n",
      "('Devland Pagett', 'Russia', Decimal('112.50'))\n",
      "('Lyndel Rodwell', 'Bangladesh', Decimal('187.50'))\n",
      "('Coralie Keenlayside', 'Indonesia', Decimal('252.41'))\n",
      "('Kameko Cockton', 'Thailand', Decimal('252.41'))\n",
      "('Cecilia Swinbourne', 'Portugal', Decimal('104.07'))\n",
      "('Dodi Lenglet', 'China', Decimal('480.00'))\n",
      "('Eyde Ellerton', 'Portugal', Decimal('139.70'))\n",
      "('Locke Janaway', 'Indonesia', Decimal('480.00'))\n",
      "('Jozef Godson', 'Brazil', Decimal('66.86'))\n",
      "('George Woodeson', 'Spain', Decimal('66.86'))\n",
      "('Tricia Bellsham', 'Venezuela', Decimal('330.00'))\n",
      "('Vaughan Gorch', 'Guatemala', Decimal('352.50'))\n",
      "('Maybelle Bellows', 'Canada', Decimal('187.50'))\n",
      "('Karel Welband', 'Czech Republic', Decimal('125.99'))\n",
      "('Livvyy Grombridge', 'Brazil', Decimal('112.50'))\n",
      "('Alison Jamieson', 'Brazil', Decimal('137.76'))\n",
      "('Dodi Basindale', 'Cuba', Decimal('139.70'))\n",
      "('Raye Fyldes', 'Colombia', Decimal('480.00'))\n",
      "('Chris Gummer', 'Indonesia', Decimal('78.12'))\n",
      "('Stephi Broose', 'Brazil', Decimal('137.76'))\n",
      "('Christen Jedrachowicz', 'South Africa', Decimal('465.00'))\n",
      "('Sindee Drynan', 'Samoa', Decimal('480.00'))\n",
      "('Mill Lambell', 'Peru', Decimal('465.00'))\n",
      "('Sayer Goudman', 'Brazil', Decimal('352.50'))\n",
      "('Amaleta Brattan', 'Indonesia', Decimal('152.40'))\n",
      "('Merrill Baudon', 'Japan', Decimal('330.00'))\n",
      "('Saw Aspenlon', 'Argentina', Decimal('104.07'))\n",
      "('Kym Lepard', 'Portugal', Decimal('480.00'))\n",
      "('Tammara Burgyn', 'Poland', Decimal('187.50'))\n",
      "('Lorna Bogart', 'Russia', Decimal('152.40'))\n",
      "('Virginie Lammas', 'Belarus', Decimal('480.00'))\n",
      "(\"Lawrence O'Cahey\", 'Portugal', Decimal('480.00'))\n",
      "('Galina Whaites', 'China', Decimal('216.14'))\n",
      "('Sorcha Beesley', 'Azerbaijan', Decimal('66.86'))\n",
      "('Borden Hacking', 'Indonesia', Decimal('78.12'))\n",
      "('Allie Turbard', 'Indonesia', Decimal('179.70'))\n",
      "('Skippy McIlwain', 'Vietnam', Decimal('125.99'))\n",
      "('Roth Cousans', 'Nigeria', Decimal('199.76'))\n",
      "(\"Mikael O'Keevan\", 'Brazil', Decimal('179.70'))\n",
      "('Haslett Jenkyn', 'China', Decimal('112.50'))\n",
      "('Adham Heyns', 'Ukraine', Decimal('112.50'))\n",
      "('Granger Aiers', 'Poland', Decimal('104.07'))\n",
      "('Antonella Ochterlony', 'Czech Republic', Decimal('186.93'))\n",
      "('Liam Downing', 'Philippines', Decimal('179.70'))\n",
      "('Dal Raper', 'China', Decimal('352.50'))\n",
      "('Salem Morgen', 'China', Decimal('147.00'))\n",
      "('Henryetta Kempster', 'Moldova', Decimal('285.00'))\n",
      "('Emmerich Ochterlony', 'Belarus', Decimal('252.41'))\n",
      "('Jakie Bullan', 'Brazil', Decimal('252.41'))\n",
      "('Reta Leipoldt', 'Indonesia', Decimal('330.00'))\n",
      "('Cele Dunster', 'Ukraine', Decimal('125.99'))\n",
      "('Calvin Aucock', 'Indonesia', Decimal('137.76'))\n",
      "('Pietra Dibdall', 'Mexico', Decimal('216.14'))\n",
      "('Steward Lavies', 'Indonesia', Decimal('104.07'))\n",
      "('Ludwig Fuxman', 'Brazil', Decimal('104.07'))\n",
      "('Konrad Standering', 'China', Decimal('104.07'))\n",
      "('Hana Livesay', 'China', Decimal('186.93'))\n",
      "('Shelbi Grishakov', 'Micronesia', Decimal('252.41'))\n",
      "('Jarib Cranke', 'Kazakhstan', Decimal('465.00'))\n",
      "('Trixy Southwick', 'Czech Republic', Decimal('125.99'))\n",
      "('Barb Murfett', 'Canada', Decimal('137.76'))\n",
      "('Roch Panchen', 'Brazil', Decimal('147.00'))\n",
      "('Doug Logg', 'Russia', Decimal('465.00'))\n",
      "('Willi Voce', 'China', Decimal('337.50'))\n",
      "(\"Cynthea O'Hickee\", 'France', Decimal('465.00'))\n",
      "('Germaine Vallack', 'Russia', Decimal('480.00'))\n",
      "('Henrie Ledward', 'Argentina', Decimal('199.76'))\n",
      "('Brook Begent', 'Latvia', Decimal('125.99'))\n",
      "('Antonino McMains', 'Philippines', Decimal('187.50'))\n",
      "('Bibbie Bover', 'Kyrgyzstan', Decimal('137.76'))\n",
      "('Boniface Giovannilli', 'Poland', Decimal('352.50'))\n",
      "(\"Halette O'Hanley\", 'China', Decimal('112.50'))\n",
      "('Nertie Igglesden', 'Spain', Decimal('315.00'))\n",
      "('Flem Haibel', 'South Korea', Decimal('104.07'))\n",
      "('Florella Reape', 'Colombia', Decimal('66.86'))\n",
      "('Carroll Tear', 'Italy', Decimal('252.41'))\n",
      "('Stephanie Uman', 'Japan', Decimal('104.07'))\n",
      "('Annmarie Bountiff', 'Morocco', Decimal('337.50'))\n",
      "('Melodee Gartshore', 'United States', Decimal('199.76'))\n",
      "('Clive Crammy', 'China', Decimal('337.50'))\n",
      "('Shandeigh Andreas', 'Portugal', Decimal('330.00'))\n",
      "('Gwenora Beauchamp', 'Zambia', Decimal('78.12'))\n",
      "('Granville Mallison', 'China', Decimal('480.00'))\n",
      "('Mart Malsher', 'Russia', Decimal('285.00'))\n",
      "('Maryellen Gligori', 'Morocco', Decimal('216.14'))\n",
      "('Zolly Heinzel', 'Poland', Decimal('179.70'))\n",
      "('Gerta Hehir', 'Mauritius', Decimal('186.93'))\n",
      "('Herculie Eastment', 'Indonesia', Decimal('330.00'))\n",
      "('Reuben Iannello', 'Sweden', Decimal('147.00'))\n",
      "('Debbie Noteyoung', 'Afghanistan', Decimal('125.99'))\n",
      "('Wandie Yeeles', 'Venezuela', Decimal('252.41'))\n",
      "('Gualterio Paget', 'Colombia', Decimal('352.50'))\n",
      "('Brandon Cocklie', 'Saint Barthelemy', Decimal('480.00'))\n",
      "('Jenn Josephoff', 'Iran', Decimal('104.07'))\n",
      "('Brynn Roset', 'Honduras', Decimal('66.86'))\n",
      "('Ximenez Meredith', 'Mali', Decimal('152.40'))\n",
      "('Alberik Fancy', 'Indonesia', Decimal('78.12'))\n",
      "('Malchy Huddlestone', 'Czech Republic', Decimal('179.70'))\n",
      "('Saul Parsonage', 'Indonesia', Decimal('187.50'))\n",
      "('Nicole Linnit', 'China', Decimal('104.07'))\n",
      "('Verena Garman', 'Indonesia', Decimal('112.50'))\n",
      "('Melita Drinkale', 'China', Decimal('139.70'))\n",
      "('Emilie Faircley', 'Sweden', Decimal('179.70'))\n",
      "('Alida Dumphy', 'Philippines', Decimal('199.76'))\n",
      "(\"Danna O'Nion\", 'Greece', Decimal('216.14'))\n",
      "(\"Korney O'Carney\", 'Canada', Decimal('137.76'))\n",
      "('Tanner Garner', 'Mexico', Decimal('186.93'))\n",
      "('Cathee Briscam', 'Germany', Decimal('112.50'))\n",
      "('Hurlee Dhennin', 'China', Decimal('139.70'))\n",
      "('Gardy Neljes', 'Peru', Decimal('480.00'))\n",
      "('Gerta Sanday', 'China', Decimal('199.76'))\n",
      "('Vincent Boarer', 'Belarus', Decimal('186.93'))\n",
      "('Gabey Macewan', 'Philippines', Decimal('465.00'))\n",
      "('Pen Pruce', 'Armenia', Decimal('179.70'))\n",
      "('Padraic Zanutti', 'Bosnia and Herzegovina', Decimal('480.00'))\n",
      "('Joanie Swindley', 'Russia', Decimal('337.50'))\n",
      "('Leslie Noden', 'Honduras', Decimal('187.50'))\n",
      "('Lilyan Schohier', 'China', Decimal('179.70'))\n",
      "('Gawain Willmont', 'Russia', Decimal('137.76'))\n",
      "('Leonora Tullett', 'Kenya', Decimal('147.00'))\n",
      "('Ilario Michie', 'Nigeria', Decimal('330.00'))\n",
      "('Rosaleen Ionnisian', 'Uzbekistan', Decimal('199.76'))\n",
      "('Berkley Petrashov', 'Argentina', Decimal('152.40'))\n",
      "('Alberik Rowcastle', 'Kenya', Decimal('252.41'))\n",
      "('Kenna Lideard', 'South Africa', Decimal('179.70'))\n",
      "('Veronique Caramuscia', 'Albania', Decimal('78.12'))\n",
      "('Brook Rainger', 'Syria', Decimal('465.00'))\n",
      "('Baxy Dunkerley', 'China', Decimal('216.14'))\n",
      "('Pauline Danihelka', 'Philippines', Decimal('137.76'))\n",
      "('Ag Gasking', 'France', Decimal('147.00'))\n",
      "('Veradis Tiddy', 'Poland', Decimal('199.76'))\n",
      "('Tibold MacGorley', 'Indonesia', Decimal('330.00'))\n",
      "('Mary Jellett', 'United States', Decimal('199.76'))\n",
      "('Charisse Risso', 'Greece', Decimal('199.76'))\n",
      "('Riccardo Jahner', 'Russia', Decimal('330.00'))\n",
      "('Terry Iannitti', 'Portugal', Decimal('199.76'))\n",
      "('Horatio Lundy', 'China', Decimal('252.41'))\n",
      "('Tiertza Doogan', 'Russia', Decimal('112.50'))\n",
      "('Jerrome Drohan', 'Indonesia', Decimal('147.00'))\n",
      "('Maressa Fruish', 'Nepal', Decimal('285.00'))\n",
      "('Cirilo Koschek', 'Croatia', Decimal('125.99'))\n",
      "('Ario Meekin', 'China', Decimal('104.07'))\n",
      "('Caterina Rosenzwig', 'Indonesia', Decimal('147.00'))\n",
      "('Dicky Van der Son', 'Russia', Decimal('66.86'))\n",
      "('Meg Reburn', 'China', Decimal('480.00'))\n",
      "('Marielle Buffey', 'Botswana', Decimal('137.76'))\n",
      "('Moishe Constant', 'Albania', Decimal('147.00'))\n",
      "('Krishnah Pearch', 'Brazil', Decimal('66.86'))\n",
      "('Jory Glave', 'Philippines', Decimal('186.93'))\n",
      "('Carlin Brabon', 'Brazil', Decimal('465.00'))\n",
      "('Joline Cancelier', 'France', Decimal('480.00'))\n",
      "('Kellby Quarterman', 'Philippines', Decimal('315.00'))\n",
      "('Dorise Reames', 'Sweden', Decimal('152.40'))\n",
      "('Felice Fiddler', 'Ukraine', Decimal('187.50'))\n",
      "('Malina Pengelly', 'Indonesia', Decimal('152.40'))\n",
      "('Kathleen Mac Giolla Pheadair', 'Ecuador', Decimal('187.50'))\n",
      "('Esra Mc Meekan', 'China', Decimal('315.00'))\n",
      "('Carol-jean Croston', 'China', Decimal('186.93'))\n",
      "('Durante Bullers', 'Peru', Decimal('139.70'))\n",
      "('Koo Vinick', 'Poland', Decimal('216.14'))\n",
      "('Spenser Wandless', 'China', Decimal('137.76'))\n",
      "('Jard Adderson', 'China', Decimal('330.00'))\n",
      "('Jehu Dauney', 'Indonesia', Decimal('66.86'))\n",
      "('Kele Bracknell', 'Indonesia', Decimal('139.70'))\n",
      "('Orelle Beadel', 'China', Decimal('199.76'))\n",
      "('Jere Whitebrook', 'Indonesia', Decimal('147.00'))\n",
      "('Cornelia Rowth', 'Japan', Decimal('152.40'))\n",
      "('Ogdon Petr', 'Canada', Decimal('104.07'))\n",
      "('Keane Wait', 'Mexico', Decimal('147.00'))\n",
      "('Harry Beak', 'China', Decimal('66.86'))\n",
      "('Enriqueta Kirwin', 'Finland', Decimal('352.50'))\n",
      "('Evan Goldsbury', 'Russia', Decimal('125.99'))\n",
      "('Hymie Meadowcroft', 'Argentina', Decimal('352.50'))\n",
      "('Ives Armstead', 'Indonesia', Decimal('480.00'))\n",
      "('Chauncey Barrott', 'Philippines', Decimal('187.50'))\n",
      "('Noel Ladley', 'Japan', Decimal('137.76'))\n",
      "('Roanna Safont', 'United States', Decimal('315.00'))\n",
      "('Gregg Yellowlea', 'South Africa', Decimal('78.12'))\n",
      "('Elisabetta Jacke', 'Philippines', Decimal('352.50'))\n",
      "('Thorny Westrip', 'Greece', Decimal('352.50'))\n",
      "('Janeva Silman', 'United States', Decimal('315.00'))\n",
      "('Karissa Sancraft', 'United States', Decimal('139.70'))\n",
      "('Kore Smurfit', 'Indonesia', Decimal('186.93'))\n",
      "('Devonne Yanuk', 'China', Decimal('187.50'))\n",
      "('Lorette Golsthorp', 'China', Decimal('66.86'))\n",
      "('Amye Limbert', 'Myanmar', Decimal('480.00'))\n",
      "(\"Tatiania O'Crigane\", 'Ukraine', Decimal('104.07'))\n",
      "('Mateo Wightman', 'Russia', Decimal('179.70'))\n",
      "('Filmer Floyd', 'Mexico', Decimal('252.41'))\n",
      "('Sheela Stein', 'United States', Decimal('187.50'))\n",
      "('Wyn Attwoull', 'Pakistan', Decimal('186.93'))\n",
      "('Elvira Beverstock', 'Portugal', Decimal('179.70'))\n",
      "('Law Leinweber', 'Indonesia', Decimal('216.14'))\n",
      "('Gallagher Benyon', 'China', Decimal('337.50'))\n",
      "('Stormi Duddin', 'South Africa', Decimal('147.00'))\n",
      "('Sharon Lazare', 'Peru', Decimal('352.50'))\n",
      "('Giustina Thorne', 'Palestinian Territory', Decimal('465.00'))\n",
      "('Faith Grushin', 'United States', Decimal('78.12'))\n",
      "('Isador Saffen', 'Thailand', Decimal('179.70'))\n",
      "('Biddy Spadoni', 'Indonesia', Decimal('139.70'))\n",
      "('Laney Fadden', 'China', Decimal('187.50'))\n",
      "('Gloriane Allsepp', 'Brazil', Decimal('179.70'))\n",
      "('Florella McMullen', 'China', Decimal('125.99'))\n",
      "('Marys Offen', 'Argentina', Decimal('337.50'))\n",
      "('Desiri Issac', 'Philippines', Decimal('112.50'))\n",
      "('Cleon Moreton', 'China', Decimal('352.50'))\n",
      "('Judy Swainson', 'Croatia', Decimal('112.50'))\n",
      "('Mable Browncey', 'Indonesia', Decimal('179.70'))\n",
      "('Alard Briat', 'Russia', Decimal('480.00'))\n",
      "('Basil Slarke', 'Russia', Decimal('139.70'))\n",
      "('Felita Dovey', 'China', Decimal('216.14'))\n",
      "('Shanan Mingay', 'China', Decimal('78.12'))\n",
      "('Isac Crimpe', 'France', Decimal('147.00'))\n",
      "('Elladine Kobiela', 'Dominican Republic', Decimal('186.93'))\n",
      "('Rhody Dobbin', 'Philippines', Decimal('179.70'))\n",
      "('Mady McMennum', 'United States', Decimal('216.14'))\n",
      "('Melisse Southeran', 'Ukraine', Decimal('337.50'))\n",
      "('Charita Bosworth', 'Poland', Decimal('152.40'))\n",
      "('Audie Willcocks', 'Portugal', Decimal('337.50'))\n",
      "('Ulick Tebboth', 'Russia', Decimal('179.70'))\n",
      "('Anders Stowe', 'China', Decimal('330.00'))\n",
      "('Prudence Eastlake', 'Sweden', Decimal('199.76'))\n",
      "('Elayne Karet', 'China', Decimal('78.12'))\n",
      "('Carlye Chiswell', 'Greece', Decimal('179.70'))\n",
      "('Hermione Crix', 'China', Decimal('78.12'))\n",
      "('Karoline Pocock', 'Philippines', Decimal('216.14'))\n",
      "('Pail Duignan', 'Saudi Arabia', Decimal('125.99'))\n",
      "('Vivie Twinning', 'Yemen', Decimal('147.00'))\n",
      "('Anjela Shobrook', 'Somalia', Decimal('480.00'))\n",
      "('Artair Lant', 'Russia', Decimal('66.86'))\n",
      "('Charline Warriner', 'Sweden', Decimal('352.50'))\n",
      "('Francis Runciman', 'China', Decimal('78.12'))\n",
      "('Asia McNess', 'Portugal', Decimal('147.00'))\n",
      "('Shell Oldis', 'China', Decimal('137.76'))\n",
      "('Gay Skechley', 'China', Decimal('186.93'))\n",
      "(\"Harriett O'Sirin\", 'Portugal', Decimal('66.86'))\n",
      "('Maighdiln Lamswood', 'China', Decimal('199.76'))\n",
      "('Carree Jeffree', 'Indonesia', Decimal('66.86'))\n",
      "('Berte Tootin', 'Thailand', Decimal('66.86'))\n",
      "('Madelin Giacomi', 'Armenia', Decimal('480.00'))\n",
      "('Aldric Jerman', 'China', Decimal('179.70'))\n",
      "('Donni Tatem', 'United States', Decimal('137.76'))\n",
      "('Silva Addy', 'Russia', Decimal('330.00'))\n",
      "('Lynsey Ludlamme', 'China', Decimal('216.14'))\n",
      "('Garek Gearty', 'Japan', Decimal('104.07'))\n",
      "('Igor Durrand', 'China', Decimal('315.00'))\n",
      "('Jethro Fenwick', 'Colombia', Decimal('139.70'))\n",
      "('Harlie Jindracek', 'Malawi', Decimal('285.00'))\n",
      "('Roxine Humphries', 'Cuba', Decimal('285.00'))\n",
      "('Alister Stronack', 'Indonesia', Decimal('285.00'))\n",
      "('Hebert Aubin', 'Colombia', Decimal('315.00'))\n",
      "('Fax Rojahn', 'Japan', Decimal('187.50'))\n",
      "('Merlina Lermit', 'United States', Decimal('352.50'))\n",
      "('Dre Danher', 'China', Decimal('199.76'))\n",
      "('Beryl Coo', 'Venezuela', Decimal('330.00'))\n",
      "('Roi Critzen', 'Russia', Decimal('352.50'))\n",
      "('Willa Wethered', 'Thailand', Decimal('352.50'))\n",
      "('Launce Sowerbutts', 'Morocco', Decimal('187.50'))\n",
      "('Grenville Penburton', 'China', Decimal('352.50'))\n",
      "('Mona Rudwell', 'Nigeria', Decimal('137.76'))\n",
      "('Ashil Brogini', 'Japan', Decimal('152.40'))\n",
      "('Adiana Shirtliff', 'Belarus', Decimal('125.99'))\n",
      "('Evangeline Bernet', 'China', Decimal('139.70'))\n",
      "('Pete Morden', 'China', Decimal('125.99'))\n",
      "('Aaron Cromley', 'Portugal', Decimal('337.50'))\n",
      "('Dusty Yedall', 'United States', Decimal('352.50'))\n",
      "('Lana Boyne', 'China', Decimal('352.50'))\n",
      "('Dore Coyett', 'Malaysia', Decimal('186.93'))\n",
      "('Reg Lepper', 'Comoros', Decimal('137.76'))\n",
      "('Anastasia Baudy', 'China', Decimal('139.70'))\n",
      "('Shandy Sefton', 'Russia', Decimal('465.00'))\n",
      "('Melisandra Mungham', 'China', Decimal('137.76'))\n",
      "('Josiah Thayre', 'Philippines', Decimal('199.76'))\n",
      "('Julie Brandes', 'Lithuania', Decimal('465.00'))\n",
      "('Cullie McBrady', 'Portugal', Decimal('480.00'))\n",
      "('Quinn Stamps', 'Malaysia', Decimal('125.99'))\n",
      "('Sabina Corneille', 'Indonesia', Decimal('480.00'))\n",
      "('Karoly Ivie', 'Pakistan', Decimal('252.41'))\n",
      "('Haskel Bowell', 'China', Decimal('137.76'))\n",
      "('Erika Greensmith', 'Democratic Republic of th', Decimal('137.76'))\n",
      "('Phil Schapero', 'Indonesia', Decimal('187.50'))\n",
      "('Staci Coppens', 'Indonesia', Decimal('285.00'))\n",
      "('Valerye Phorsby', 'Indonesia', Decimal('186.93'))\n",
      "('Zena Todari', 'Indonesia', Decimal('179.70'))\n",
      "('Gordan Hitscher', 'Indonesia', Decimal('147.00'))\n",
      "('Rowan Grover', 'Colombia', Decimal('199.76'))\n",
      "('Alexia Candelin', 'Finland', Decimal('480.00'))\n",
      "('Giacopo Bramich', 'North Korea', Decimal('352.50'))\n",
      "('King Hillin', 'Thailand', Decimal('104.07'))\n",
      "('Cirillo Creamen', 'China', Decimal('139.70'))\n",
      "('Christoper Myrkus', 'China', Decimal('187.50'))\n",
      "('Gale Reeves', 'Nepal', Decimal('66.86'))\n",
      "('Eba Harriagn', 'Argentina', Decimal('139.70'))\n",
      "('Aldin Purrier', 'Germany', Decimal('465.00'))\n",
      "('Garvin Guerrazzi', 'China', Decimal('330.00'))\n",
      "('Winn Raynes', 'Indonesia', Decimal('104.07'))\n",
      "('Windham Meekin', 'Indonesia', Decimal('66.86'))\n",
      "(\"Douglas O' Cloney\", 'Philippines', Decimal('252.41'))\n",
      "('Bianka McLanaghan', 'Indonesia', Decimal('315.00'))\n",
      "('Ravid Josephsen', 'Sweden', Decimal('252.41'))\n",
      "('Martainn Van Zon', 'Thailand', Decimal('252.41'))\n",
      "('Bradford Rafe', 'Senegal', Decimal('480.00'))\n",
      "('Kelsy Schroder', 'Indonesia', Decimal('147.00'))\n",
      "('Lia Bonar', 'Peru', Decimal('112.50'))\n",
      "('Kalinda Grestye', 'China', Decimal('137.76'))\n",
      "('Fredelia Snedden', 'Indonesia', Decimal('139.70'))\n",
      "('Dell Hellsdon', 'Montenegro', Decimal('125.99'))\n",
      "('Bree Bleas', 'China', Decimal('139.70'))\n",
      "('Berte Cornall', 'Nepal', Decimal('125.99'))\n",
      "('Gualterio Backshall', 'Brazil', Decimal('179.70'))\n",
      "('Marillin Dennehy', 'Senegal', Decimal('139.70'))\n",
      "('Annaliese Cowill', 'Nicaragua', Decimal('139.70'))\n",
      "('Mary Demangel', 'Poland', Decimal('352.50'))\n",
      "('Kelbee Illesley', 'Brazil', Decimal('252.41'))\n",
      "('Arlette Magauran', 'Armenia', Decimal('465.00'))\n",
      "('Marchelle Annes', 'Ukraine', Decimal('112.50'))\n",
      "('Yorgo Muzzillo', 'Indonesia', Decimal('112.50'))\n",
      "('Carolan Di Giacomo', 'China', Decimal('112.50'))\n",
      "('Reilly Domonkos', 'Portugal', Decimal('187.50'))\n",
      "('Richie Brydson', 'United States', Decimal('216.14'))\n",
      "('Verene Beatens', 'Portugal', Decimal('252.41'))\n",
      "('Mei Scrogges', 'Russia', Decimal('147.00'))\n",
      "('Gus Trower', 'Indonesia', Decimal('330.00'))\n",
      "('Marcelia Kerswell', 'Cuba', Decimal('137.76'))\n",
      "('Hanni Dunbleton', 'China', Decimal('112.50'))\n",
      "('Sarah Plaschke', 'Thailand', Decimal('480.00'))\n",
      "('Renato Paulin', 'United States', Decimal('480.00'))\n",
      "('Essy Licence', 'Philippines', Decimal('137.76'))\n",
      "('Roxana Dicte', 'Mexico', Decimal('186.93'))\n",
      "('Ash Boise', 'China', Decimal('147.00'))\n",
      "('Chloette Pyke', 'China', Decimal('147.00'))\n",
      "('Angel Veschambre', 'Mexico', Decimal('315.00'))\n",
      "('Devonne Whal', 'Colombia', Decimal('104.07'))\n",
      "('Row Colchett', 'Indonesia', Decimal('465.00'))\n",
      "('Nels Ordish', 'Burkina Faso', Decimal('480.00'))\n",
      "('Brendin Meedendorpe', 'Maldives', Decimal('187.50'))\n",
      "('Allyce Mantione', 'Russia', Decimal('152.40'))\n",
      "(\"Jill O'Sirin\", 'Japan', Decimal('187.50'))\n",
      "('Zita Coldbath', 'China', Decimal('78.12'))\n",
      "('Darby McLae', 'North Korea', Decimal('112.50'))\n",
      "('Killy Condie', 'Russia', Decimal('179.70'))\n",
      "('Cyndi Ruler', 'Croatia', Decimal('337.50'))\n",
      "('Leanna Chapelhow', 'France', Decimal('78.12'))\n",
      "('Mattie Winyard', 'China', Decimal('315.00'))\n",
      "('Alli Cunney', 'China', Decimal('186.93'))\n",
      "('Armstrong Collerd', 'Philippines', Decimal('216.14'))\n",
      "('Lauri Hughill', 'Indonesia', Decimal('330.00'))\n",
      "('Nels Hargreaves', 'Micronesia', Decimal('125.99'))\n",
      "('Elliott Avard', 'Czech Republic', Decimal('465.00'))\n",
      "('Sterne Salterne', 'United States', Decimal('285.00'))\n",
      "('Christian Yeld', 'Indonesia', Decimal('330.00'))\n",
      "('Erv Padrick', 'Thailand', Decimal('147.00'))\n",
      "('Tamarah Filasov', 'Indonesia', Decimal('104.07'))\n",
      "('Katherine Midson', 'Serbia', Decimal('104.07'))\n",
      "('Belle Priver', 'Russia', Decimal('186.93'))\n",
      "('Inez Flade', 'Portugal', Decimal('125.99'))\n",
      "('Berny Elcoate', 'Argentina', Decimal('112.50'))\n",
      "('Jillene Maro', 'Philippines', Decimal('78.12'))\n",
      "('Julietta Legerwood', 'Thailand', Decimal('66.86'))\n",
      "('Anastasie Jahnisch', 'Tunisia', Decimal('179.70'))\n",
      "('Wynnie Feronet', 'China', Decimal('187.50'))\n",
      "('Mirilla Barff', 'China', Decimal('139.70'))\n",
      "('Neely Frankcomb', 'China', Decimal('465.00'))\n",
      "('Laverna Skeermer', 'China', Decimal('125.99'))\n",
      "('Carol-jean Sodory', 'China', Decimal('125.99'))\n",
      "('Donella Tomasini', 'Norway', Decimal('216.14'))\n",
      "('Margarette Hobell', 'Ireland', Decimal('104.07'))\n",
      "('Fred Tatersale', 'Bolivia', Decimal('465.00'))\n",
      "('Estele Schultze', 'Russia', Decimal('285.00'))\n",
      "('Celle Oller', 'Sweden', Decimal('112.50'))\n",
      "('Ximenes Carnachen', 'Kazakhstan', Decimal('285.00'))\n",
      "('Laina Thurborn', 'Mongolia', Decimal('66.86'))\n",
      "('Kaleena Philips', 'Indonesia', Decimal('152.40'))\n",
      "('Maisie Matyushkin', 'China', Decimal('216.14'))\n",
      "('Merill Leyninye', 'Poland', Decimal('252.41'))\n",
      "('Ara McWard', 'Macedonia', Decimal('104.07'))\n",
      "('Jefferson Lauderdale', 'Indonesia', Decimal('104.07'))\n",
      "('Claybourne Costin', 'Greece', Decimal('66.86'))\n",
      "('Marketa Olman', 'Indonesia', Decimal('465.00'))\n",
      "('Egbert Mollnar', 'Ukraine', Decimal('187.50'))\n",
      "('Crysta Garratty', 'Philippines', Decimal('337.50'))\n",
      "('Emmalynne Hairs', 'Indonesia', Decimal('112.50'))\n",
      "('Farrel Teare', 'Albania', Decimal('179.70'))\n",
      "('Phillis Denley', 'Indonesia', Decimal('125.99'))\n",
      "('Petronille Scrimgeour', 'United States', Decimal('285.00'))\n",
      "('Ernestine Merrgen', 'Indonesia', Decimal('78.12'))\n",
      "('Alaric Thaw', 'Sweden', Decimal('125.99'))\n",
      "('Burke Jupp', 'Russia', Decimal('104.07'))\n",
      "('Caterina Sweetnam', 'Philippines', Decimal('139.70'))\n",
      "('Julianna Jostan', 'Philippines', Decimal('187.50'))\n",
      "('Kipp Coulling', 'Portugal', Decimal('137.76'))\n",
      "('Sandy Rubinowicz', 'China', Decimal('147.00'))\n",
      "('Isidro Chelam', 'Russia', Decimal('465.00'))\n",
      "(\"Rodrigo D'Alessio\", 'Trinidad and Tobago', Decimal('186.93'))\n",
      "('Onfroi Kornyakov', 'Philippines', Decimal('147.00'))\n",
      "('Emera Whitewood', 'Ecuador', Decimal('465.00'))\n",
      "('Melessa Lecordier', 'Albania', Decimal('330.00'))\n",
      "('Doreen Sothcott', 'United States', Decimal('480.00'))\n",
      "('Amandie Rohmer', 'Latvia', Decimal('285.00'))\n",
      "('Ferdinand Fowley', 'Uganda', Decimal('315.00'))\n",
      "('Dinny Fonzone', 'Indonesia', Decimal('337.50'))\n",
      "('Dian Collough', 'China', Decimal('199.76'))\n",
      "('Rayner Lukianovich', 'Indonesia', Decimal('186.93'))\n",
      "('Purcell Eyer', 'Kazakhstan', Decimal('186.93'))\n",
      "('Eleonore Stitcher', 'China', Decimal('337.50'))\n",
      "('Mariel Bourdel', 'Indonesia', Decimal('252.41'))\n",
      "('Hersh Bolgar', 'South Korea', Decimal('315.00'))\n",
      "('Rivi Bowart', 'Bangladesh', Decimal('104.07'))\n",
      "('Ash Lodford', 'China', Decimal('112.50'))\n",
      "('Emilee Riddeough', 'Kazakhstan', Decimal('337.50'))\n",
      "('Gothart Domesday', 'Georgia', Decimal('216.14'))\n",
      "('Red Nordass', 'Indonesia', Decimal('337.50'))\n",
      "('Aubine Chardin', 'Philippines', Decimal('252.41'))\n",
      "('Carney Speer', 'Portugal', Decimal('152.40'))\n",
      "('Nancy Rollinshaw', 'Canada', Decimal('147.00'))\n",
      "('Seamus Hearl', 'Belarus', Decimal('352.50'))\n",
      "('Dwain Eccott', 'Pakistan', Decimal('152.40'))\n",
      "('Perrine Scalera', 'Indonesia', Decimal('78.12'))\n",
      "('Esdras Scoffins', 'Indonesia', Decimal('285.00'))\n",
      "('Adamo Rumens', 'Mongolia', Decimal('285.00'))\n",
      "('Sander Maloney', 'Sweden', Decimal('337.50'))\n",
      "('Ibrahim Jurries', 'Portugal', Decimal('330.00'))\n",
      "('Amandi McConaghy', 'Tunisia', Decimal('186.93'))\n",
      "('Beth Crocket', 'Japan', Decimal('147.00'))\n",
      "('Polly Murton', 'Philippines', Decimal('125.99'))\n",
      "('Celine Coopland', 'Indonesia', Decimal('186.93'))\n",
      "('Renard Crispin', 'Portugal', Decimal('125.99'))\n",
      "('Viviyan Lantiff', 'Philippines', Decimal('252.41'))\n",
      "('Ferrel Jeratt', 'China', Decimal('147.00'))\n",
      "('Ginelle Finnimore', 'Azerbaijan', Decimal('352.50'))\n",
      "('Berenice Marples', 'Ukraine', Decimal('465.00'))\n",
      "('Griz Tawse', 'Indonesia', Decimal('216.14'))\n",
      "('Rafferty Guyonneau', 'Philippines', Decimal('137.76'))\n",
      "('Hamnet Coultas', 'Japan', Decimal('285.00'))\n",
      "('Hale Danilchik', 'Indonesia', Decimal('285.00'))\n",
      "('Selia Grigoroni', 'Indonesia', Decimal('252.41'))\n",
      "('Marice Leavens', 'China', Decimal('199.76'))\n",
      "('Anabelle Dominelli', 'Greece', Decimal('352.50'))\n",
      "('Adah Adamczewski', 'China', Decimal('285.00'))\n",
      "('Baldwin Colchett', 'Mali', Decimal('66.86'))\n",
      "('Claire Morland', 'Cuba', Decimal('330.00'))\n",
      "('Fredi Helks', 'Japan', Decimal('125.99'))\n",
      "('Fairfax Seniour', 'Slovenia', Decimal('139.70'))\n",
      "('Patrizia Kunrad', 'China', Decimal('147.00'))\n",
      "('Andrej Wolfindale', 'Philippines', Decimal('285.00'))\n",
      "('Lorne Boldry', 'United States', Decimal('78.12'))\n",
      "('Charline Windrus', 'China', Decimal('147.00'))\n",
      "('Kerri Barnes', 'Brazil', Decimal('252.41'))\n",
      "('Brunhilda Beeze', 'Brazil', Decimal('352.50'))\n",
      "('Sheilah Maestro', 'Russia', Decimal('465.00'))\n",
      "('Linus Gresham', 'Costa Rica', Decimal('104.07'))\n",
      "('Chastity Medlar', 'Indonesia', Decimal('337.50'))\n",
      "('Kissie Gosford', 'Indonesia', Decimal('104.07'))\n",
      "('Tommi Durham', 'Indonesia', Decimal('352.50'))\n",
      "('Lucretia Whyborn', 'Peru', Decimal('337.50'))\n",
      "('Eimile Matz', 'Indonesia', Decimal('252.41'))\n",
      "('Janeva Buist', 'France', Decimal('199.76'))\n",
      "('Winnah Laye', 'Indonesia', Decimal('330.00'))\n",
      "('Dolorita Drayton', 'Bahrain', Decimal('337.50'))\n",
      "('Debbi Gaule', 'France', Decimal('125.99'))\n",
      "('Flynn Magnay', 'Poland', Decimal('252.41'))\n",
      "('Agnes Acey', 'Belarus', Decimal('352.50'))\n",
      "('Lenore Tabb', 'China', Decimal('330.00'))\n",
      "('Rorie Colicot', 'China', Decimal('199.76'))\n",
      "('Read Trusty', 'Thailand', Decimal('147.00'))\n",
      "('Valida Greenhill', 'Philippines', Decimal('352.50'))\n",
      "('Emelda Furbank', 'Zimbabwe', Decimal('252.41'))\n",
      "('Hilary Pudner', 'Philippines', Decimal('139.70'))\n",
      "('Les Harmson', 'Russia', Decimal('147.00'))\n",
      "('Tony Crabtree', 'China', Decimal('125.99'))\n",
      "('Mitzi De Mico', 'Indonesia', Decimal('152.40'))\n",
      "('Des Covet', 'Finland', Decimal('337.50'))\n",
      "('Montgomery Spileman', 'Russia', Decimal('285.00'))\n",
      "('Klement Brothwell', 'Peru', Decimal('337.50'))\n",
      "('Rooney Milbourne', 'Lithuania', Decimal('315.00'))\n",
      "('Jameson Yaknov', 'Indonesia', Decimal('337.50'))\n",
      "('Ber Dillet', 'Jamaica', Decimal('147.00'))\n",
      "('Tove Jaquest', 'Nigeria', Decimal('199.76'))\n",
      "('Hyacintha Hanne', 'United States', Decimal('147.00'))\n",
      "('Sabra Corry', 'Japan', Decimal('285.00'))\n",
      "('Pincas Stearn', 'Germany', Decimal('78.12'))\n",
      "('Josephine Archer', 'China', Decimal('465.00'))\n",
      "('Enid Francescuccio', 'Albania', Decimal('252.41'))\n",
      "('Manolo Russ', 'Indonesia', Decimal('112.50'))\n",
      "('Brittni Nielson', 'Colombia', Decimal('199.76'))\n",
      "('Gennifer Koenen', 'Ecuador', Decimal('186.93'))\n",
      "('Marlo McGeaney', 'China', Decimal('66.86'))\n",
      "('Wenona MacGinlay', 'United States', Decimal('199.76'))\n",
      "('Henryetta Kunes', 'Netherlands', Decimal('337.50'))\n",
      "('Adelheid Casolla', 'Indonesia', Decimal('252.41'))\n",
      "('Terrye Littlechild', 'China', Decimal('330.00'))\n",
      "('Mack Fabri', 'Uruguay', Decimal('315.00'))\n",
      "('Giselle Abrahart', 'Poland', Decimal('78.12'))\n",
      "('Hynda Skeel', 'Wallis and Futuna', Decimal('315.00'))\n",
      "('Mattie Brenston', 'China', Decimal('252.41'))\n",
      "('Codee Pindar', 'Greece', Decimal('315.00'))\n",
      "('Dyanne Labbet', 'Indonesia', Decimal('152.40'))\n",
      "('Del Hughman', 'China', Decimal('199.76'))\n",
      "('Ram Chaudhry', 'Namibia', Decimal('480.00'))\n",
      "('Danyelle Butts', 'China', Decimal('137.76'))\n",
      "('Yorgos BoHlingolsen', 'Portugal', Decimal('285.00'))\n",
      "('Davita Baynham', 'Croatia', Decimal('315.00'))\n",
      "('Tamma Clink', 'United States', Decimal('352.50'))\n",
      "('Leonard Fuxman', 'Argentina', Decimal('480.00'))\n",
      "('Britta Barday', 'Indonesia', Decimal('199.76'))\n",
      "('Nita Vannacci', 'Iran', Decimal('330.00'))\n",
      "('Adria Heller', 'Indonesia', Decimal('285.00'))\n",
      "('Henry Reaney', 'Brazil', Decimal('480.00'))\n",
      "('Abigail Struis', 'China', Decimal('152.40'))\n",
      "('Deck Paulat', 'Portugal', Decimal('186.93'))\n",
      "('Ephrem Steers', 'Canada', Decimal('216.14'))\n",
      "('Alexandros Brookfield', 'China', Decimal('125.99'))\n",
      "('Ennis Dungate', 'Panama', Decimal('66.86'))\n",
      "('Kristian Beeken', 'Ecuador', Decimal('285.00'))\n",
      "('Zach Bondley', 'Indonesia', Decimal('125.99'))\n",
      "('Manuel Gloyens', 'China', Decimal('285.00'))\n",
      "('Linus Greer', 'Afghanistan', Decimal('465.00'))\n",
      "('Dannye Passmore', 'Czech Republic', Decimal('139.70'))\n",
      "('Tasia Fautly', 'Libya', Decimal('480.00'))\n",
      "('Torr Windrus', 'China', Decimal('337.50'))\n",
      "('Leanna Dur', 'Brazil', Decimal('315.00'))\n",
      "('Rene Garn', 'Uganda', Decimal('352.50'))\n",
      "('Dieter Crannis', 'Cuba', Decimal('147.00'))\n",
      "('Paddie Tellenbrok', 'Russia', Decimal('78.12'))\n",
      "('Viva Foulstone', 'Poland', Decimal('199.76'))\n",
      "(\"Jo O'Nowlan\", 'Syria', Decimal('199.76'))\n",
      "('Kristoffer Pales', 'France', Decimal('465.00'))\n",
      "('Tera Stockdale', 'France', Decimal('152.40'))\n",
      "('Mano Abrahamson', 'Portugal', Decimal('480.00'))\n",
      "('Sinclare Milburne', 'Greece', Decimal('152.40'))\n",
      "('Becki Bonsall', 'China', Decimal('199.76'))\n",
      "('Aldrich Phythien', 'United States', Decimal('78.12'))\n",
      "('Adria Koubu', 'Canada', Decimal('152.40'))\n",
      "('Dru Priscott', 'Czech Republic', Decimal('66.86'))\n",
      "('Sid Oultram', 'Philippines', Decimal('285.00'))\n",
      "('Steven Cornbell', 'Hungary', Decimal('315.00'))\n",
      "('Mariquilla Labbe', 'Togo', Decimal('337.50'))\n",
      "('Arthur Mathewson', 'China', Decimal('139.70'))\n",
      "('Christi Flute', 'China', Decimal('465.00'))\n",
      "('Sullivan Eddoes', 'Portugal', Decimal('125.99'))\n",
      "('Lisle Scamadin', 'Czech Republic', Decimal('216.14'))\n",
      "('Kim McCloughlin', 'Nigeria', Decimal('315.00'))\n",
      "('Cissiee Gobeau', 'Uzbekistan', Decimal('186.93'))\n",
      "('Sibley Rodder', 'Ukraine', Decimal('152.40'))\n",
      "('Elfrieda Umbers', 'Russia', Decimal('216.14'))\n",
      "('Sabra Calbreath', 'Czech Republic', Decimal('352.50'))\n",
      "('Gearard Rowston', 'Netherlands', Decimal('104.07'))\n",
      "('Demetris McGibbon', 'Italy', Decimal('480.00'))\n",
      "('Ethelbert Cordeux', 'Finland', Decimal('78.12'))\n",
      "('Audra Hebborn', 'Indonesia', Decimal('152.40'))\n",
      "('Henrie Karolovsky', 'Russia', Decimal('139.70'))\n",
      "('Cate Pagitt', 'Peru', Decimal('125.99'))\n",
      "('Lise Fegan', 'Afghanistan', Decimal('199.76'))\n",
      "('Persis Chipchase', 'Indonesia', Decimal('330.00'))\n",
      "('Burgess Hancill', 'Madagascar', Decimal('137.76'))\n",
      "('Olive Jeannon', 'Russia', Decimal('186.93'))\n",
      "('Steward Doyland', 'Philippines', Decimal('352.50'))\n",
      "('Phillipe Ropartz', 'Micronesia', Decimal('147.00'))\n",
      "('Brit Northfield', 'Indonesia', Decimal('139.70'))\n",
      "('Melicent Gieves', 'Indonesia', Decimal('337.50'))\n",
      "('Sheffield Turbitt', 'Japan', Decimal('315.00'))\n",
      "('Bonnee Keller', 'China', Decimal('216.14'))\n",
      "('Alexandr McGill', 'China', Decimal('78.12'))\n",
      "('Kali Avis', 'Greece', Decimal('137.76'))\n",
      "('Vania Gilding', 'Brazil', Decimal('66.86'))\n",
      "('Leonie Battin', 'Russia', Decimal('179.70'))\n",
      "('Sherye Christmas', 'United States', Decimal('216.14'))\n",
      "('Janith Bowra', 'Nigeria', Decimal('66.86'))\n",
      "('Malinde Blunn', 'Indonesia', Decimal('139.70'))\n",
      "('Sophey Garling', 'China', Decimal('285.00'))\n",
      "('Delilah Ayerst', 'Indonesia', Decimal('480.00'))\n",
      "('Payton Rissen', 'Philippines', Decimal('147.00'))\n",
      "('Elisabetta Dubery', 'Mozambique', Decimal('137.76'))\n",
      "('Gabrielle Coxall', 'China', Decimal('137.76'))\n",
      "('Cissy Blondelle', 'Russia', Decimal('179.70'))\n",
      "('Maddalena Wolfinger', 'Zambia', Decimal('465.00'))\n",
      "('Jerrie Jiran', 'Brazil', Decimal('125.99'))\n",
      "('Hilly Leahey', 'China', Decimal('152.40'))\n",
      "('Ardenia Lobb', 'China', Decimal('104.07'))\n",
      "('Johnette Haitlie', 'Ivory Coast', Decimal('104.07'))\n",
      "('Shannon Osban', 'China', Decimal('480.00'))\n",
      "('Deina Agus', 'Colombia', Decimal('78.12'))\n",
      "('Dene Dawby', 'Saint Lucia', Decimal('78.12'))\n",
      "('Bentley Gwyneth', 'China', Decimal('137.76'))\n",
      "('Quintus Parcells', 'Norway', Decimal('186.93'))\n",
      "('Jessalin Dimitriades', 'Indonesia', Decimal('125.99'))\n",
      "('Gordan Kneeshaw', 'Russia', Decimal('78.12'))\n",
      "('Wilek Ivanyushkin', 'Ethiopia', Decimal('66.86'))\n",
      "('Lowrance Kleinmintz', 'China', Decimal('252.41'))\n",
      "('Cornall Pimlock', 'Poland', Decimal('337.50'))\n",
      "('Kathy Fairlam', 'China', Decimal('187.50'))\n",
      "('Doll Friary', 'Russia', Decimal('187.50'))\n",
      "('Cornela LaBastida', 'China', Decimal('216.14'))\n",
      "('Fanni Caccavella', 'Philippines', Decimal('104.07'))\n",
      "('Anny Pattemore', 'Indonesia', Decimal('285.00'))\n",
      "('Raye Rossant', 'Albania', Decimal('465.00'))\n",
      "('Licha Verden', 'Brazil', Decimal('187.50'))\n",
      "('Lauralee Beteriss', 'Sweden', Decimal('285.00'))\n",
      "('Riley Curnnok', 'Jersey', Decimal('186.93'))\n",
      "('Candy Simoncelli', 'China', Decimal('216.14'))\n",
      "('Vale Norwood', 'United States', Decimal('252.41'))\n",
      "('Sly Fullwood', 'Peru', Decimal('139.70'))\n",
      "('Hall Everil', 'Ukraine', Decimal('152.40'))\n",
      "('Webster Lomax', 'Czech Republic', Decimal('252.41'))\n",
      "('Jacynth Clubb', 'Poland', Decimal('285.00'))\n",
      "('Cathe Snar', 'China', Decimal('137.76'))\n",
      "('Katrina Aylett', 'France', Decimal('104.07'))\n",
      "('Monique Fry', 'Bangladesh', Decimal('125.99'))\n",
      "('Jacquetta Plampin', 'China', Decimal('187.50'))\n",
      "('Ellis Castanares', 'China', Decimal('147.00'))\n",
      "('Nadine Cudbird', 'China', Decimal('187.50'))\n",
      "('Jaynell Alty', 'Uruguay', Decimal('112.50'))\n",
      "('Skipp Lowater', 'Peru', Decimal('315.00'))\n",
      "('Cori Percifer', 'Mexico', Decimal('465.00'))\n",
      "('Tiler Kenrack', 'Canada', Decimal('330.00'))\n",
      "('Willow Burmingham', 'Myanmar', Decimal('139.70'))\n",
      "('Allyn Gurnay', 'Vietnam', Decimal('315.00'))\n",
      "('Lucho McGerraghty', 'Indonesia', Decimal('216.14'))\n",
      "('Jemmy Whelan', 'Brazil', Decimal('125.99'))\n",
      "('Ellis Kops', 'France', Decimal('285.00'))\n",
      "('Marsiella Duprey', 'Japan', Decimal('480.00'))\n",
      "('Kimberli Eisenberg', 'Peru', Decimal('186.93'))\n",
      "('Serena Yerby', 'France', Decimal('112.50'))\n",
      "('Paxon Jeffcoat', 'Russia', Decimal('66.86'))\n",
      "('Rici Bollin', 'Poland', Decimal('112.50'))\n",
      "('Alisander Shoebottom', 'Philippines', Decimal('330.00'))\n",
      "('Lance Cheatle', 'United States', Decimal('179.70'))\n",
      "('Marsh Fransoni', 'Russia', Decimal('186.93'))\n",
      "('Alisander Cornelisse', 'Russia', Decimal('179.70'))\n",
      "('Rania Gerritsma', 'Zimbabwe', Decimal('152.40'))\n",
      "('Howie Flamank', 'Brazil', Decimal('352.50'))\n",
      "('Mariann Ibbeson', 'Indonesia', Decimal('78.12'))\n",
      "('Lilian Dislee', 'Brazil', Decimal('179.70'))\n",
      "('Ainslee Feighney', 'Brazil', Decimal('112.50'))\n",
      "('Nessie Wheal', 'China', Decimal('352.50'))\n",
      "('Titos Edgcumbe', 'Greece', Decimal('78.12'))\n",
      "('Barby Noell', 'Philippines', Decimal('315.00'))\n",
      "('Gilberta Sabberton', 'Panama', Decimal('125.99'))\n",
      "('Hervey Ganning', 'Brazil', Decimal('199.76'))\n",
      "('Adlai Arnull', 'Saudi Arabia', Decimal('337.50'))\n",
      "('Christoforo Vagg', 'Brazil', Decimal('139.70'))\n",
      "('Malinde Firbanks', 'Indonesia', Decimal('112.50'))\n",
      "('Virgie Belhomme', 'Uganda', Decimal('187.50'))\n",
      "('Madlin McGrory', 'China', Decimal('112.50'))\n",
      "('Jolee Linthead', 'Indonesia', Decimal('152.40'))\n",
      "('Todd Riglesford', 'Philippines', Decimal('78.12'))\n",
      "('Clarette Barreau', 'China', Decimal('330.00'))\n",
      "('Leone Klulisek', 'Tanzania', Decimal('352.50'))\n",
      "('Sharai MacMenamin', 'Russia', Decimal('285.00'))\n",
      "('Zebedee Spafford', 'Indonesia', Decimal('199.76'))\n",
      "('Lucais Sewards', 'China', Decimal('252.41'))\n",
      "('Merrill Sawford', 'Indonesia', Decimal('179.70'))\n",
      "('Felix Ouver', 'Czech Republic', Decimal('179.70'))\n",
      "('Rana Rait', 'Brazil', Decimal('137.76'))\n",
      "('Chrotoem Harniman', 'Zambia', Decimal('187.50'))\n",
      "('Joye MacHostie', 'Russia', Decimal('186.93'))\n",
      "('Rayna Strathearn', 'China', Decimal('179.70'))\n",
      "('Mellicent Philliphs', 'Brazil', Decimal('139.70'))\n",
      "('Natka Featenby', 'Russia', Decimal('152.40'))\n",
      "('Ariadne Copeland', 'United States', Decimal('187.50'))\n",
      "('Ferguson Wilcocke', 'Russia', Decimal('252.41'))\n",
      "('Yardley Eliet', 'United States', Decimal('315.00'))\n",
      "('Raven Cawkwell', 'Indonesia', Decimal('104.07'))\n"
     ]
    }
   ],
   "source": [
    "cursor.execute(query)\n",
    "results = cursor.fetchall()\n",
    "\n",
    "for row in results:\n",
    "    print(row)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e4890de-aad9-44de-8f3d-4adca7fd833f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
